### ISSUE TITLE
Deal with dot inconsistency

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#101]
We have a "dot" operation for vectors of eigen type, but not for, e.g., tpetra or tpetra_block. For consistency, I propose we either eliminate dot from the ops package for eigen, or add the "dot" operation to all types.

This issue arose when Patrick tried to build the new LM solver I wrote with an application using tpetra types. The solver used dot and was tested with an eigen FOM, so it wasn't flagged.

**Comment by eparish1** [comment]
We should fix this sooner rather than later. This issue popped up again in issue #136

**Comment by fnrizzi** [comment]
@eparish1 i will fix this next few days, it will be in the new release

**Comment by eparish1** [comment]
@fnrizzi Sounds good. Here is a solution for Kokkos (I wanted to do some testing of the line searches). I'll plan on not adding this to the repo unless you want me to.
'''cpp
template <typename vec_type>
::pressio::mpl::enable_if_t<
  containers::predicates::is_vector_wrapper_kokkos<vec_type>::value,
  typename ::pressio::containers::details::traits<vec_type>::scalar_t
  >
dot(const vec_type & x,
    const vec_type & y)
{
  using sc_t = typename ::pressio::containers::details::traits<vec_type>::scalar_t;
  sc_t result = {};
  assert( y.extent(0) == x.extent(0) );
  result = KokkosBlas::dot(*x.data(), *y.data() );
  return result;
}

'''

**Comment by fnrizzi** [comment]
@eparish1 sounds good, I will use this :)
