### ISSUE TITLE
rom: support for variable Jacobians

### ISSUE THREAD

**Issue by jtencer** [Pressio/pressio#107]
For nonlinear manifold ROMs, the Jacobian is a function of the ROM state.  To facilitate this, I propose that the signature for `getReferenceToJacobian()` be modified to take the ROM state as an argument.  For linear ROMs, this would be unused.

**Comment by fnrizzi** [comment]
@eparish1 we need to talk at some point about how to update the decoder's jacobian in WLS. 
if we can do it as we do in LSPG and Galerkin, then great, just want to make sure for WLS some other restrictions come up
