### ISSUE TITLE
syntax for mask

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#120]
@eparish1 @pjb236 @jtencer @vbrunini 

for the mask, do you need the current state or we don't need it?  so which of the following do you prefer: 

With state passed in: 
```c++
  void applyMask(const state_type &, const residual_type & unmaskedObj,     residual_type & maskedObj) const;
  void applyMask(const state_type &, const dense_matrix_type & unmaskedObj, dense_matrix_type & maskedObj) const;
```
Without state: 
```c++
  void applyMask(const residual_type & unmaskedObj,     residual_type & maskedObj) const;
  void applyMask(const dense_matrix_type & unmaskedObj, dense_matrix_type & maskedObj) const;
```
also, both share these: 
```c++
  residual_type createApplyMaskResult(const residual_type & unmaskedObj) const;
  dense_matrix_type createApplyMaskResult(const dense_matrix_type & unmaskedObj) const;
```

**Comment by fnrizzi** [comment]
right now I am using the one WITH state, just because it is more general

**Comment by eparish1** [comment]
I would advocate for not including the state. I can't think of a situation where the state alone would be beneficial for the mask.

**Comment by fnrizzi** [comment]
@eparish1 but it could have information to use for apply the mask, don't you think?

**Comment by pjb236** [comment]
I agree with @eparish1, I don't think the state will be used by the mask.

**Comment by fnrizzi** [comment]
ok i will remove it :)
so in sparc now it is not used?

**Comment by pjb236** [comment]
No, the cells in the mask are obtained from a user-specified array of cell IDs.

**Comment by fnrizzi** [comment]
@pjb236 @eparish1 what about the preconditioner? do yuu need the current state for that or not? 
```c++
  void applyPreconditioner(const state_type &, residual_type & r) const;
```

**Comment by pjb236** [comment]
Keep the current state as an input. There are situations where we could need the state. For example, if we are using an approximate Jacobian as the preconditioner, we would need the state to compute that approximation.
