### ISSUE TITLE
solvers: custom observer object for monitoring nonlinear solvers

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#125]
spawned from #121 

scope: design a new way to enable users to monitor convergence of nonlinear solvers

**Comment by fnrizzi** [comment]
Quoting @eparish1 

I have worked with a few CFD codes that have had this type of capability, and I think the cleanest implementation for this is in the form of a "hook". The hook gets called at, e.g., each time step, each nonlinear iteration. We come up with a list of reasonable inputs to the hook, and then the user can do whatever they want with them by writing their own hook. For example, printing out state norms, post processing. I believe that this should be done independently of the print statements, however.

**Comment by pjb236** [comment]
We can set up the hook to call the operator for a custom diagnostic object that we pass to the nonlinear solver, ODE, or ROM objects. The question is whether these should override the default printouts, append to the default printouts, or both.

**Comment by fnrizzi** [comment]
i think we have this or something similar, so closing for now
