### ISSUE TITLE
Add code to initialize all wls coefficients over a window

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#129]
In the current implementation of wls, the initial guess for the wlsState into a window is either the solution from the previous window, or if we are at the first window it is whatever the user initializes wlsState to be. At the start of a window, we should add code to set the wlsState over the whole window to either be the solution from the last step of the last window, or if we are at the first window it should be what was initialized in the constructor.

**Comment by eparish1** [comment]
@fnrizzi do you mind if I merge the push for this?

**Comment by fnrizzi** [comment]
@eparish1 go ahead! I just checked, it was just a small code, I thought it was much more!
