### ISSUE TITLE
rom: abstraction for creating ROM problems with specific types and settings

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#141]
Need abstraction for creating ROM problems with specific types and settings. 
Need to simply creation of ROM problems because right now there are many types involved.  
Right now, one has to specify the full details of: 
- types, decoder, ROM problem, solver 

It would be nice to have a way to compose a full "problem" such that the user only describes what they want, but pressio takes care of composing types properly. 

Things to specify to define a problem vary based on algorithm. 
- steady LSPG: 
  - mapping type (linear or custom) 
  - lib to solve the ROM (eigen, Kokkos)
  - nonlin least-squares solver to use: gaussNewtonWithNEQ, gnWithQR, etc

- unsteady LSPG: 
  - mapping type (linear or custom) 
  - lib to solve the ROM (eigen, Kokkos)
  - time stepping scheme 
  - nonlin least-squares solver to use: gaussNewtonWithNEQ, gnWithQR, etc

- Galerkin - explicit
  - mapping type (linear or custom) 
  - lib to solve the ROM (eigen, Kokkos)
  - time stepping scheme 

- Galerkin - implicit
  - mapping type (linear or custom) 
  - lib to solve the ROM (eigen, Kokkos)
  - time stepping scheme 
  - nonlin solver: only Newton-Raphson available now

**Comment by jtencer** [comment]
Should we have the linear mapping as just a special case of the custom mapping?

**Comment by fnrizzi** [comment]
@jtencer good point! I was thinking about it and looked at it today.
In the case above, linear/custom is just a way for pressio to compose the algorithms' types properly and detect compatibility issues, etc. Because what happens if one wants a linear mapping from pressio is different from a custom mapping. In the linear mapping case, one has to provide only the decoder jacobian (if types are supported) but for a custom mapping, one has to pass the full mapping object. So it changes how one constructs things. 
But making different abstractions is easy, so I am not worried about that :) 
The custom mapping is really something pressio has no control on. I like to keep it that way. But a user is free to just use a custom mapping all the time, even to implement a linear one.

**Comment by fnrizzi** [comment]
I am thinking something where you describe the problem and the words reflect what you want: 
```c++
using reduced_order_problem = pressio::rom::composeDefaultUnsteadyLSPGWithLinearMapping(
      useEigenToSolveROM, useGaussNewtonWithNormalEquations, 
      <some-other-args-needed>)
```
or similar, finding the best naming will be the key :) but I like the descriptive/expressive nature.

**Comment by fnrizzi** [comment]
```c++
auto problem = compose_{default,preconditioned,masked}_{steady,unsteady}_{LSPG,Galerkin,WLS}
(/* args */)

auto problem = compose_default_unsteady_LSPG(/* args , phi */) // this implies linear mapping
auto problem = compose_default_unsteady_LSPG(/* args , O */) // O is object that is a custom mapper

```
