### ISSUE TITLE
Improve hyper reduction for non-Trillinos applications

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#144]
I believe it is worth considering adding new capabilities for hyper reduction. As I understand it, presently we only provide native support for Trillinos applications. I would argue hyper reduction is the most important aspect of ROMs for nonlinear problems, so we should really focus on it.

My first thought for a generic implementation is that we could have two decoders:  Phi1 that maps from the generalized coordinates to the queried residual cells, and Phi2 that maps from the generalized coordinates to the queried residual cells + the stencil cells. We work with Phi1 in most places, with the exception of using Phi2 to reconstruct a fom state that is then passed to the application. 

I can write this out in more detail in the future.

**Comment by fnrizzi** [comment]
@eparish1 

What about we enable two different ways to do HR. 

- scenarioA: for doing HR, we call an external function to assemble the discrete_time operators. 
We can do something like this: 
```c++
using namespace pressio::rom:lspg;
using problem_t = typename composeHyperReducedDefaultProblem<ode_tag, fom_t, lspg_state_t, decoder_t, ops_t>::type;
problem_t lspgProb(fomObj, yRef, decoder, yROM, t0, opsObject);
```

- scenarioB: we support your stuff too
