### ISSUE TITLE
LM damping parameter needs to get updated for sequential calls to the solver.

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#146]
Self explanatory. This got lost and didn't trigger the unit tests as they were only checking one solve.

**Comment by eparish1** [comment]
@fnrizzi let me know if you'd like me to add this. I think we could just add a resetSolver method to the solver operators, and then call that in the solve_untils at the first step.

**Comment by fnrizzi** [comment]
@eparish1 working on it now since i also changed the setting of the convergence, will push a 0.4.1 patch today
