### ISSUE TITLE
rom: linear decoder, take Jacobian by reference

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#147]

**Comment by fnrizzi** [comment]
decided not to do this, so that the LinearDecoder **owns** its jacobian matrix. 
This way it is pressio responsible for the lifetime of this object and therefore we ensure things cannot be messed up. 
This is in line with what we do for the FOM states, because FOM states are owned by Pressio.  

Basically, this is a contract with the user (and an assurance) saying: once you create the LinearDecoder, pressio owns its parts. If you need to use its Jacobian matrix, you need to carry around the decoder object  itself. 
This also encourage the user to do something: 
```c++
using mapper_t = pressio::LinearDecoder<...>;

mapper_t createLinearMapper(...)
{
  mapper_t myMapper(...);
  return myMapper;
}

auto myLinearMapper = createLinearMapper(...);
```
which we know would leverage the RVO such that no copy is made and a single instance of the mapper exists.

**Comment by eparish1** [comment]
I think this is fine, but it would be helpful if we made it as clear as
possible in the documentation that this is the case, as the basis is the
heaviest part of the ROM. Duplicating it could be the difference between
being able to run a ROM and not being able to.

**Comment by fnrizzi** [comment]
@eparish1 yes, I agree. If done right, there is no duplication. Also, the worst scenario is one where the copy happens only once.
