### ISSUE TITLE
tpls: add libtorch

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#148]

**Comment by jtencer** [comment]
https://pytorch.org/cppdocs/installing.html

**Comment by fnrizzi** [comment]
@jtencer can you please commit to the `torch` branch the model to use for the your Burgers example ? 
So I can reproduce it? how big is the file?

**Comment by jtencer** [comment]
It should be there.  https://github.com/Pressio/pressio/commit/367b50c7bfc7fdcc505f57c83e97c0a50b40bfb8

139114

**Comment by jtencer** [comment]
tests/rom/burgers1d/basis/decoder_ncell100_romsize8_t30_dt_001_implicit_euler.pt

**Comment by fnrizzi** [comment]
@jtencer thanks! sorry, i missed it! 
Just making sure, this is a portable file format? Because if we leave it in the tests, we need it to be portable

**Comment by jtencer** [comment]
It should be as portable as TorchScript is.

**Comment by jtencer** [comment]
I noticed that the other tests all use a coarser mesh (only 20 cells instead of 100).  I can update that test to use a 20 cell mesh so that the test runs faster.

**Comment by fnrizzi** [comment]
let me look at it and then we can see if it needs to be modfied. 
btw, are you building on mac or linux? 
I get a strange error when building on mac.
```
ld: unknown option: --no-as-needed
collect2: error: ld returned 1 exit status
```

**Comment by jtencer** [comment]
linux.  I haven't tried it on any other platform.

**Comment by fnrizzi** [comment]
ok , it will try to fix it

**Comment by fnrizzi** [comment]
enabled on linux only 01699971ee60f591efc8c6d87aa38b5691fadc2d
but this is not final because i still need to fix
