### ISSUE TITLE
extent(0) for a tpetraBlockVector inconsistency

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#155]
Say x is a tPetraBlockVector of block size 3 with 50 entries. x.extent(0) returns 50, it should probably return 150.

**Comment by fnrizzi** [comment]
@eparish1 i see your point, but I believe this is right. 
In my view, the vector should have extent 50 because that is the number of blocks in the vector. The fact that each entry contains 3 subelements is a separate concept.
Does this make sense?

**Comment by eparish1** [comment]
@fnrizzi Ok, got it! I have a slightly different view. As pressio doesn't have the concept of a blockVector, I expected pressio to view a blockVector as just a flattened, longer vector. This mindset was why I posted the issue - I thought it was an error. I think it is fine as is, as long as its consistent everywhere which it sounds like it is.

**Comment by fnrizzi** [comment]
@eparish1 You raise a good point! If it makes more sense, maybe we should change it. let me think about it :)
