### ISSUE TITLE
Implicit Galerkin with Residual Generates NaNs in convergence criterion

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#157]
When I try running the Implicit Galerkin Residual API with epetra vectors, it computes NaNs when dividing by the gradientNorm0, which in my case is 0.0. The specific case has a Galerkin DefaultProblem type, with a HouseholderQR-based linear solver and NewtonRaphson nonlinear solver.

**Comment by fnrizzi** [comment]
@pjb236 can you please paste here the commit of pressio you are using? because I think this is fixed in 0.4.1

**Comment by pjb236** [comment]
496b46b, the latest develop branch

**Comment by fnrizzi** [comment]
@pjb236 when you say it "computes NaN" it means you get an error? or what? In theory, you should not even see  any logging about the gradient for the problem you are solving, am i right? basically it should only print the correction norm, aboslute and relative residual norm. am i right?
