### ISSUE TITLE
Feature request: state dependant time stepping

### ISSUE THREAD

**Issue by samajors** [Pressio/pressio#158]
Request: add support for optional API function along the lines of
`scalar_type getdt(scalar_type t, state_type u)`
so that the user can specify logic to select the next time step based on the current time and state

(could also include number of elapsed time steps as a parameter if user would rather base scheduling on that than elapsed time)

**Comment by fnrizzi** [comment]
see https://github.com/Pressio/pressio/blob/develop/tests/rom/burgers1d/lspg/eigen/lspg_euler_normal_eq_user_dt_setter/main.cc
