### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ppebay** [Pressio/pressio#17]
This issue is mostly to discuss how documentation shall and will be improved. In particular, we should consider using the embedded Wiki.

**Comment by mperrinel** [comment]
I give here my first feedback on the doc :

1) Cmake and bash Prerequisites section explains that different versions will be verified later. It is true ? Important ?
Most of people doesn't care about their Cmake version until they have a problem on it. I suggest to only give the min version

2) How can we test that the tutorial installation works ?  We can read from the log that tutorial 1, 2 and 3 have been created. I think that in addition, a section which explains how to execute them and shows that all is working could be nice.

In addition in the Wiki of the Pressio / pressio-tutorials : 
- Add a Contacts section 
- Add a link to the Pressio description 

Also what is the current plan for the Pressio / pressio wiki itself ?

**Comment by fnrizzi** [comment]
Wiki now is terrible... so I agree on all of the above ;)
