### ISSUE TITLE
rom: support cases with mass matrix 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#173]
Might need to have an additional call to the user-defined app like: 
```c++
void applyMassMatrix(...)
```
with syntax to be defined.

**Comment by pjb236** [comment]
This is essential for setting up the velocity API for finite element discretizations. It will also help with finite volume because we will no longer need to divide the velocity vector by cell volume.

**Comment by pjb236** [comment]
> An important thing to consider here as well is orthogonality of the bases. Let's say we have a mass matrix M. It makes sense to construct the basis vectors such that \Phi^T M \Phi = I, which yields simplifications. For LSPG this doesn't matter (I don't think), but for the Galerkin ROM it definitely does.

Also, we could use the mass matrix interface as part of an SVD routine to enforce orthogonality in the correct norm. At a minimum, we could use it to output the mass matrix in a sparse format so we could read it in with snapshots.

**Comment by fnrizzi** [comment]
We decided to check if adapter has mass matrix, and if so we call it

**Comment by pjb236** [comment]
> We decided to check if adapter has mass matrix, and if so we call it

We might want to add print statements and/or warnings if a mass matrix is found or not found.

**Comment by fnrizzi** [comment]
closing since this is super seeded by other more detailed issues on this
