### ISSUE TITLE
rom: norms for masked problem should compute the right norm

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#187]
Currently if you create a preconditioned LSPG problem with the continuou-time API, when the solver evaluates the norm of the residual it computes the **unpreconditioned** norm. This is my mistake :( 
It should compute the norm of the preconditioned residual. 
(similarly for a masked problem, #187 )

**Comment by fnrizzi** [comment]
@eparish1 @pjb236 @jtencer agree on this?

**Comment by pjb236** [comment]
Agreed. I think it's always good to compute the right thing instead of the wrong thing.

**Comment by fnrizzi** [comment]
I am assuming you don't need both right?
