### ISSUE TITLE
rom: add rom-specific functions to solve and advance in time  

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#226]
It is useful to add functions like: 
```c++
rom::lspg::advanceNSteps(romProblemObj)
```
where the function takes the rom problem object. 
Currently, the user is supposed to use `ode::advanceNSteps(stepper)` by explicitly extrcting the stepper object from the romProblem.

**Comment by fnrizzi** [comment]
@eparish1 @pjb236 @jtencer @vbrunini thoughts on the following? 

After we create a target LSPG problem, we need to run/solve it. 
Currently, to do this we do the following: 
```c++
// construct LSPG problem 
auto lspgProblem = pressio::rom::lspg::createDefaultProblemUnsteady(...); // or some other unsteady LSPG variant

// extract the stepper object 
auto & stepper = lspgProblem.stepper();

// advance in time, which can be done, e.g. using:
pressio::ode::advanceNSteps(stepper, /*something else*/); 
//or
pressio::ode::advanceToTargetTime(stepper, ...);
//or
pressio::ode::advanceToTargetTimeWithTimeStepRecovery(stepper, ...)

```
Note that the `advance` functions are within `namespace ode`.
This is ok, but to me it feels a bit more complex/counter intuitive than needed. It kind of depends on the interpretation of what LSPG is. If we interpret LSPG as a sequence of minimization problems, then we could improve this. 
I would still leave the above choice as valid, since there is nothing wrong with it. 
But, in addition, I was thinking of adding abstractions as follows: 
```c++
auto lspgProblem = pressio::rom::lspg::createDefaultProblemUnsteady(...); // or some other unsteady LSPG variant 
pressio::rom::lspg::solveOverNSteps(rom_problem_type & problem, ...);

// or we could highlight the "minimization" aspect of LSPG by using these variants for the fixed steps: 
pressio::rom::lspg::solveNTimes(problem, ...) 
pressio::rom::lspg::minimizeNTimes(problem, ...)
pressio::rom::lspg::peformNMinimizationsOn(problem, ...)

// these variants for the until case: 
pressio::rom::lspg::solveUntilTime(problem, ...) 
pressio::rom::lspg::minimizeUntilTime(problem, ...)
// these variants for the case we recover the step: 
pressio::rom::lspg::solveUntilTimeWithRecovery(problem, ...) 
pressio::rom::lspg::minimizeUntilTimeWithRecovery(problem, ...)

```
Note that now these new functions are within the `namespace rom`, accept the LSPG problem object directly, and we effectively hide the fact that we are doing a time stepping. *However* one would still need to pass a time-step size as argument to the above function, because it is obviously needed. The concept of time is still present. Also because LSPG is really based on discretizing and then minimize, so time is inherently present. The other benefit of the new approach is that we don't explicitly make users get the stepper.

**Comment by eparish1** [comment]
I think the best aspect of this is removing the dependency on the stepper. I agree with everything you said. For LSPG, I would advocate for  something like:
```c++
pressio::rom::lspg::solveSequentialResMinProblemsNTimes

pressio::rom::lspg::solveSequentialResMinProblemsUntileTime
```
