### ISSUE TITLE
Improve IO when we use the armijo rule

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#235]
I/0 when we use the armijo rule looks like this:

 ^[[36m NonlinearIter = 2  ||Residual||_l2 (abs) = 9.491913e-08  ||Residual||_l2 (rel) = ^[[32m 9.963233e-01 ^[[00m ^[[36m ||Gradient||_l2 (abs) =  3.244465e-11  ||Gradient||_l2 (rel) = ^[[32m 4.980279e-01 ^[[00m ^[[36m ||Correction||_l2 = 8.380721e-02 ^[[00m
 backtracking: alpha = 1.000000e+00
 f(x_k+alpha*p_k) = 9.594361e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.024477e-09 ; alpha*beta*g^T p_k = -1.913420e-21
 f(x_k+alpha*p_k) = 9.522647e-08
 f(x_k+alpha*p_k)-f(x_k) = 3.073418e-10 ; alpha*beta*g^T p_k = -9.567102e-22
 f(x_k+alpha*p_k) = 9.502123e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.021014e-10 ; alpha*beta*g^T p_k = -4.783551e-22
 f(x_k+alpha*p_k) = 9.495726e-08
 f(x_k+alpha*p_k)-f(x_k) = 3.812917e-11 ; alpha*beta*g^T p_k = -2.391775e-22
 f(x_k+alpha*p_k) = 9.493496e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.583174e-11 ; alpha*beta*g^T p_k = -1.195888e-22
 f(x_k+alpha*p_k) = 9.492624e-08
 f(x_k+alpha*p_k)-f(x_k) = 7.107398e-12 ; alpha*beta*g^T p_k = -5.979439e-23
 f(x_k+alpha*p_k) = 9.492248e-08
 f(x_k+alpha*p_k)-f(x_k) = 3.351522e-12 ; alpha*beta*g^T p_k = -2.989719e-23
 f(x_k+alpha*p_k) = 9.492076e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.625196e-12 ; alpha*beta*g^T p_k = -1.494860e-23
 f(x_k+alpha*p_k) = 9.491993e-08
 f(x_k+alpha*p_k)-f(x_k) = 7.999250e-13 ; alpha*beta*g^T p_k = -7.474298e-24
 f(x_k+alpha*p_k) = 9.491953e-08
 f(x_k+alpha*p_k)-f(x_k) = 3.968043e-13 ; alpha*beta*g^T p_k = -3.737149e-24
 f(x_k+alpha*p_k) = 9.491933e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.976208e-13 ; alpha*beta*g^T p_k = -1.868575e-24
 f(x_k+alpha*p_k) = 9.491923e-08
 f(x_k+alpha*p_k)-f(x_k) = 9.857687e-14 ; alpha*beta*g^T p_k = -9.342873e-25
 f(x_k+alpha*p_k) = 9.491918e-08
 f(x_k+alpha*p_k)-f(x_k) = 4.921041e-14 ; alpha*beta*g^T p_k = -4.671436e-25
 f(x_k+alpha*p_k) = 9.491916e-08
 f(x_k+alpha*p_k)-f(x_k) = 2.456690e-14 ; alpha*beta*g^T p_k = -2.335718e-25
 f(x_k+alpha*p_k) = 9.491914e-08
 f(x_k+alpha*p_k)-f(x_k) = 1.222872e-14 ; alpha*beta*g^T p_k = -1.167859e-25
 f(x_k+alpha*p_k) = 9.491914e-08
 f(x_k+alpha*p_k)-f(x_k) = 6.110331e-15 ; alpha*beta*g^T p_k = -5.839295e-26

This is messy and hard to analyze. I don't have any specific suggestions, but it would be nice to improve the IO for this.

**Comment by fnrizzi** [comment]
I agree :)
