### ISSUE TITLE
add code coverage

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#241]
@meriadegp

**Comment by mperrinel** [comment]
@fnrizzi @ppebay 
The CI has been modified to include two news jobs containing code coverage for Pressio with or without Trilinos.
The code coverage uses gcov and gcovr tools to produce an xml report which is uploaded to codecove.io without any account.
A badge has been added to the README and reports the current pressio coverage using the master branch.
This badge will display a number the next time that develop will be merged into master.
The link to the codecove.io reports can be found from the specific coverage jobs on the github actions page.
