### ISSUE TITLE
Add comments to ops files

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#247]
We obviously have a lot of work on commenting to do, but I think we should prioritize adding comments to every operation in the /ops package that explicitly states what they are doing. I can take the lead on this.

**Comment by fnrizzi** [comment]
@eparish1 
why is that important? I would say this is not super priority for the following reasons: 
- every op file has a brief description of what is going on at the top 
- maybe for the most complex ones , like level3 yes 
- I think commenting out and documenting how to instantiate the ROM problems is higher priority in my view and finishing up the Galerkin stuff
