### ISSUE TITLE
ode: discrete api which evaluation time to pass

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#257]
If we are at time step `n`, for the discrete time api, should we query the discrete time residual by passing: 
```
currentTime + dt;
```
or 
```
currentTIme
```
where `currentTime = t_n`? We currently pass currentTime but maybe this is misleading. 

Basically, what `t` should this be getting: 
```
void discreteTimeResidual(state ..., time t, ....)
```

**Comment by fnrizzi** [comment]
@eparish1

**Comment by fnrizzi** [comment]
I am leaning towards passing `t_n + 1` since (in my view) the discrete time api is meant for implicit time stepping.

**Comment by pjb236** [comment]
> I am leaning towards passing `t_n + 1` since (in my view) the discrete time api is meant for implicit time stepping.

I agree with this, when implementing this for heat transfer I needed to update the time to "t_{n+1}" in the discrete residual function to make sure that any time-dependent boundary conditions were correct.

**Comment by eparish1** [comment]
I would also say to do currentTime + dt, assuming that at time step 0 the current time is zero. Basically, if the starting time is t_0, I would ensure that in the first time step we are passing t_0 + dt.

On Jan 4, 2021, at 1:21 PM, Patrick Blonigan <notifications@github.com<mailto:notifications@github.com>> wrote:



I am leaning towards passing t_n + 1 since (in my view) the discrete time api is meant for implicit time stepping.

I agree with this, when implementing this for heat transfer I needed to update the time to "t_{n+1}" in the discrete residual function to make sure that any time-dependent boundary conditions were correct.

**Comment by fnrizzi** [comment]
ok thanks @pjb236 @eparish1 . 

so to summarize, if we are at step `n` and need to predict solution at `n+dt`, the time `t_toevaluate` to compute the discrete-time residual we ALWAYS pass `t_toevaluate = t_n + dt`.

**Comment by eparish1** [comment]
I guess it depends if our step counter is zero based or one based. From my perspective, it should be designed as followed (assuming we start from time = 0 and have a constant time step size):

[cid:556CB0DD-5C5A-41FC-874A-6D40A250193B]

This way, t_n corresponds to t_0 + n*dt, where n is the step number.

**Comment by fnrizzi** [comment]
yes you are right. it depends. 
Currently, pressio/ode is such that: 
```
step 1 means we are going from t_0 -> t_1
step 2 from t_1 -> t_2 
step 3 from t_2 -> t_3
```
so say we are at step `4`, we are going from `t_4 -> t_5', then we should evaluate `f(y_5, t_5)`
does this make sense?

**Comment by eparish1** [comment]
I am a bit confused :) From the email, at step 4, shouldn’t we be going from t_3 -> t_4?

On Jan 4, 2021, at 2:14 PM, Francesco Rizzi <notifications@github.com<mailto:notifications@github.com>> wrote:



yes you are right. it depends.
Currently, pressio/ode is such that:

step 1 means we are going from t_0 -> t_1
step 2 from t_1 -> t_2
step 3 from t_2 -> t_3


so say we are at step 4, we are going from t_4 -> t_5', then we should evaluate f(y_5, t_5)`
does this make sense?

**Comment by fnrizzi** [comment]
Awesome! I will change the time for the discrete time api and then we are in business since I already updated all bdf methods too
