### ISSUE TITLE
rom: interface for regular LSPG using *residual API*

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#26]
The proposed *residual api* interface for LSPG. 

```c++
class RomLSPGResidualAPI{
public:
  using scalar_type = 
  using state_type = 
  using residual_type = 
  using jacobian_type = 
  using dense_matrix_type = 

public:
  template <typename step_t, typename ... Args>
  void timeDiscreteResidual(const step_t & step,
                            const scalar_type & time,
                            const scalar_type & dt,
                            residual_type & R,
                            Args && ... states) const
  {
    // forward to whatever appropriate impl method, e.g.
    // timeDiscreteResidualImpl<step_t>( step, time, dt, f, std::forward<Args>(states)... );
    // of which we have multiple overloads based on the number of states 
  }

  template <typename step_t, typename ... Args>
  residual_type timeDiscreteResidual(const step_t & step,
                                     const scalar_type & time,
                                     const scalar_type & dt,
                                     Args && ... states) const
  {
    // initialize (depends on the app and data structure types used)
    residual_type R( /*whatever_it_needs_to_be_constructed*/ );
    this->timeDiscreteResidual(step, time, R, std::forward<Args>(states)...);
    return R;
  }

  // computes: time discrete Jacobian, Jac, and then A = Jac B
  void applyTimeDiscreteJacobian(const state_type & state,
                                 const dense_matrix_type & B,
                                 const scalar_type & t,
                                 dense_matrix_type & A) const{
    // compute Jacobian 
    // compute time-discrete Jacobian 
    // apply time-discrete Jacobian to B and store into A 
  }

  // computes: time discrete Jacobian, Jac, and then A = Jac B
  dense_matrix_type applyTimeDiscreteJacobian(const state_type & state,
                    			      const dense_matrix_type & B,
                                              const scalar_type & t) const{
    dense_matrix_type A( /*whatever_it_needs_to_be_constructed*/ );
    this->applyTimeDiscreteJacobian(state, B, t, A);
    return A;
  }
};

**Comment by fnrizzi** [comment]
@pjb236 @eparish1 @vbrunini can you please take a look and give me some feedback on this? Is this intuitive?

**Comment by pjb236** [comment]
If timeDiscreteResidual requires multiple states inputs, then applyTimeDiscreteJacobian should as well. 

Also, as Eric pointed out we will need Jacobians with respect to the different input states. Perhaps we can do this with an additional input to the applyTimeDiscreteJacobian that specifies which state we want the Jacobian with respect to.

**Comment by fnrizzi** [comment]
Good point, I will change it to something like: 

```c++
// jacobian_state_id tells you which state to compute jacobian wrt 
template <int jacobian_state_id, typename ... Args>
void applyTimeDiscreteJacobian(const state_type & state,
                               const dense_matrix_type & B,
                               const scalar_type & t,
                               dense_matrix_type & A, 
                               Args & ... states) const{
  // compute Jacobian 
  // compute time-discrete Jacobian 
  // apply time-discrete Jacobian to B and store into A 
}
```

**Comment by fnrizzi** [comment]
@mhoemmen

**Comment by vbrunini** [comment]
Why a template parameter for the jacobian_state_id rather than a normal function argument?

Will the Jacobian application always be done for a state that the residual calculation has happened for (i.e. could I compute and store the Jacobian during timeDiscreteResidual to then apply during calls to applyTimeDiscreteJacobian) ?

**Comment by fnrizzi** [comment]
@vbrunini 
(a) I am ok with a normal argument too! Either one works for me. 
(b) Let me check and get back to you...

**Comment by mhoemmen** [comment]
I'm coming to this interface completely ignorant of what's going on, but I'm a bit nervous about returning residual vectors and dense matrices by value, especially if you plan for those to be (GPU) device allocations.  GPU allocations are expensive.  If the caller knows the dimensions of those returned objects, then it would be nicer to make those output arguments to which the methods write.

**Comment by fnrizzi** [comment]
@mhoemmen Totally agree. To give you a bit of a background: (a) the caller does not know the dimensions of those return object and (b) the non-void methods are only called by pressio once at the beginning to construct the objects. After that initial setup stage, pressio owns those objects and calls the void methods. Considering this is done for time-dependent problems with many steps, this is negligible. But I totally see your point. (We have on the plate the option to just "view" user-defined objects, such that it is up to the application to create them and pressio just uses them. But this is not a working feature yet.)

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> the main point, though, which I hope will make you less nervous :), is that the non-void methods are only called by pressio **once** at the beginning to construct the objects.

Ah, that's good then, I'm less worried : - )

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> I wish those objects were all default constructible....

This is a bit of a tangent, but a lot of objects of interest are default constructible.  `Tpetra::MultiVector` is, for example.

**Comment by mhoemmen** [comment]
@vbrunini wrote:
> Why a template parameter for the `jacobian_state_id` rather than a normal function argument?

I would also like to ask this question -- it looks like this is a coarse-grained function, so there is no value in making the state ID a compile-time constant.

**Comment by fnrizzi** [comment]
@mhoemmen @vbrunini I will make it an argument! (if you have a better name for it, let me know :) )

**Comment by fnrizzi** [comment]
@vbrunini @eparish1 @pjb236 one more clarification: 
- since with this new interface one can theoretically handle an arbitrary stepping scheme of which pressio knows nothing about, I was thinking of letting the full-order model handle the time step size `dt`. So basically, pressio knows nothing about the time step and if it changes or not. If you use this new interface, you are required to handle the time step yourself. Does this make sense to you? do you agree/disagree? that is the reason why `dt` does not appear in the arguments.

**Comment by eparish1** [comment]
This makes sense - and I think the first approach is better. In my opinion the selection of the time step should be on the Pressio end. Though, that might be be an issue for codes that only return the fully discrete residual.

**Comment by pjb236** [comment]
The first approach makes the most sense. It gives us the most flexibility and is the more future-proof than hiding the time step size in the adapter class. Furthermore, one of the most important knobs we have to balance ROM cost and accuracy is time step size, so we should have full control of it in pressio.

**Comment by vbrunini** [comment]
The first approach also works for me.

**Comment by fnrizzi** [comment]
Here is the latest draft of the residual API: 

```c++

class SampleResidualApi
{
public:
  using scalar_type	= //..;
  using state_type	= //...;
  using residual_type	= //...;
  using jacobian_type	= //...;
  using dense_matrix_type = //...;

public:
  template <typename step_t, typename ... Args>
  void timeDiscreteResidual(const step_t & step,
  			    const scalar_type & time,
  			    const scalar_type & dt,
  			    residual_type & R,
  			    Args && ... states) const
  {
    this->timeDiscreteResidualImpl(step, time, dt, R, std::forward<Args>(states)... );
  }

  template <typename step_t, typename ... Args>
  residual_type timeDiscreteResidual(const step_t & step,
  				     const scalar_type & time,
  				     const scalar_type & dt,
  				     Args && ... states) const
  {
    residual_type R(/* construct this somehow */);
    this->timeDiscreteResidualImpl(step, time, dt, R, std::forward<Args>(states)... );
    return R;
  }

  template <typename step_t, typename ... Args>
  void applyTimeDiscreteJacobian(const step_t & step,
  				 const scalar_type & time,
  				 const scalar_type & dt,
  				 const dense_matrix_type & B,
  				 int id,
  				 dense_matrix_type & A,
  				 Args && ... states) const
  {
    // id is the state wrt which we compute time-discrete jacobian   
    // so when id=0, it means compute J = dR/dyn (i.e. wrt current state)
    // so when id=1, it means compute J = dR/dynm1 (i.e. wrt previous)

    this->applyTimeDiscreteJacobianImpl(step, time, dt, B, id, A, std::forward<Args>(states)...);
  }

  template <typename step_t, typename ... Args>
  dense_matrix_type applyTimeDiscreteJacobian(const step_t & step,
  					      const scalar_type & time,
  					      const scalar_type & dt,
  					      const dense_matrix_type & B,
  					      int id,
  					      Args && ... states) const
  {
    // first compute the time discrete Jacobian, J, then apply it to B
    dense_matrix_type A(/* construct this somehow */;
    this->applyTimeDiscreteJacobianImpl(step, time, dt, B, id, A, std::forward<Args>(states)...);
    return A;
  }


private:
  // case when we only have a single auxiliary state, e.g. BDF1
  // add another overload if you need more auxiliary states
  template <typename step_t>
  void timeDiscreteResidualImpl(const step_t & step,
				const scalar_type & time,
				const scalar_type & dt,
				residual_type & R,
				const state_type & yn,
				const state_type & ynm1) const
  {
    // compute the time-discrete residual at t=time 
    // e.g. BDF1: R = yn - ynm1 - dt * f;
  }

  // case when we only have a single auxiliary state, e.g. BDF1
  // add another overload if you need more auxiliary states
  template <typename step_t, typename state_t>
  void applyTimeDiscreteJacobianImpl(const step_t & step,
				     const scalar_type & time,
				     const scalar_type & dt,
				     const dense_matrix_type & B,
				     int id,
				     dense_matrix_type & A,
				     const state_t & yn,
				     const state_t & ynm1) const
  {
    // id is the state wrt which we compute time-discrete jacobian   
    // so when id=0, it means compute J = dR/dyn (i.e. wrt current state)
    // so when id=1, it means compute J = dR/dynm1 (i.e. wrt previous)

    // compute Jacobian
    // compute time discrete Jacobian
    // compute A = J * B
  }
};
```

**Comment by pjb236** [comment]
This looks good to me.

**Comment by fnrizzi** [comment]
Current version: https://github.com/Pressio/pressio/wiki/Adapter-residual-based-API-for-LSPG
