### ISSUE TITLE
ode: explicit time stepping schemes

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#263]
We currently have: 
- euler forward 
- RK4 
- AdamsBashforth2 

what else? 
@eparish1 @pjb236 @jtencer

**Comment by eparish1** [comment]
I think this is probably good. My personal favorites are Jameson's low-storage RK4 (eq 11 in https://ntrs.nasa.gov/api/citations/19930006613/downloads/19930006613.pdf) and strong stability preserving RK3 (https://gkeyll.readthedocs.io/en/latest/dev/ssp-rk.html)

**Comment by pjb236** [comment]
I think these are fine as well. The only one I would consider adding is the RK3 scheme mentioned by Eric: good balance of order of accuracy and cost.
