### ISSUE TITLE
ode: implicit schemes 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#264]
Currently we have: 
- BDF1
- BDF2 
- Crank-Nicolson 

@eparish1 @jtencer @pjb236

**Comment by eparish1** [comment]
I also think this is sufficient. (S)-DIRK schemes are the next natural thing from my point of view, but I don't think they are critical right now. I doubt that ROMs need them due to decreased stiffness.

**Comment by pjb236** [comment]
I agree with Eric. I think a ROM which needs fancy implicit or imex scheme to deal with stiffness issues is probably not a ROM worth solving.
