### ISSUE TITLE
need a detailed list of ops needed for each functionality 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#293]
make list where we map ops to functionality. has to be done for each component.
For, ODE, list of examples where to start looking:
- https://github.com/Pressio/pressio/blob/main/unit_tests/ode/serial_explicit/ode_explicit_euler_user_defined_ops.cc
- https://github.com/Pressio/pressio/blob/main/unit_tests/ode/serial_explicit/ode_explicit_rk4_user_defined_ops.cc
- https://github.com/Pressio/pressio/blob/main/unit_tests/ode/serial_explicit/ode_explicit_ab2_user_defined_ops.cc

For ROM, some examples: 
- https://github.com/Pressio/pressio/blob/main/tests/rom/burgers1d/galerkin/arbitrary_data_structures/default_galerkin_euler_continuous_time_api_arb_ds/main.cc
- https://github.com/Pressio/pressio/blob/main/tests/rom/burgers1d/lspg/arbitrary_data_structures/lspg_euler_normal_eq_discrete_time_api_arb_ds/main.cc
- https://github.com/Pressio/pressio/blob/main/tests/rom/burgers1d/lspg/arbitrary_data_structures/lspg_euler_normal_eq_continuous_time_api_arb_ds/main.cc
-

Should proceed one component at a time: 
- [ ] solvers
- [ ] ode
- [ ] rom

**Comment by eparish1** [comment]
@fnrizzi Here is my first full pass with your comments

#Linear solvers breakdown



|                      | All     |
|----------------------|---------|
|mat-vec product       |   [ ]      |
|mat-mat product       |   [ ]      |
| update (3)           |   [ ]      |
|update (4)            |   [ ]      |
|update(5)             |   [ ]      | 
|update(6)             |   [ ]      | 
|update(7)             |   [ ]      | 
|update(8)             |   [ ]      | 
|update(9)             |   [ ]      | 
|update(10)            |   [ ]      | 
|norm2                 |   [ ]      | 
|set_zero              |   [ ]      | 
|dot                   |   [ ]      | 
| elementwise_multiply |   [ ]      | 
| abs_pow              |   [ ]      |  
| fill                 |   [ ]      | 
| deep_copy            |   [x]      | 
| scale                |   [ ]      | 
|  add\_to\_diagonal   |   [ ]      | 
##File breakdown
1. impl/solvers\_linear\_kokkos\_direct\_geqrf\_impl.hpp: **deep_copy**
2. impl/solvers\_linear\_kokkos\_direct\_potrs\_lower\_impl.hpp: **deep_copy**
3. impl/solvers\_linear\_kokkos\_direct\_getrs\_impl.hpp: **deep_copy**
4. impl/solvers\_linear\_kokkos\_direct\_potrs\_upper\_impl.hpp: **deep_copy**

#Nonlinear solvers breakdown

|                      | GN w/ QR   | GN w/ normal | LM w/ normal |
|----------------------|------------|--------------|--------------| 
|mat-vec product       |   [x]      |     [x]      |     [x]      |
|mat-mat product       |   [x]      |     [x]      |     [x]      |
| update (3)           |   [ ]      |     [ ]      |     [ ]      |
|update (4)            |   [x]      |     [x]      |     [x]      |
|update(5)             |   [x]      |     [x]      |     [x]      |
|update(6)             |   [ ]      |     [ ]      |     [ ]      | 
|update(7)             |   [ ]      |     [ ]      |     [ ]      | 
|update(8)             |   [ ]      |     [ ]      |     [ ]      | 
|update(9)             |   [ ]      |     [ ]      |     [ ]      | 
|update(10)            |   [ ]      |     [ ]      |     [ ]      | 
|norm2                 |   [x]      |     [x]      |     [x]      | 
|set_zero              |   [x]      |     [x]      |     [x]      | 
|dot                   |   [x]      |     [x]      |     [x]      | 
| elementwise_multiply |   [x]      |     [x]      |     [x]      | 
| abs_pow              |   [x]      |     [x]      |     [x]      | 
| fill                 |   [x]      |     [x]      |     [x]      | 
| deep_copy            |   [ ]      |     [ ]      |     [x]      | 
| scale                |   [x]      |     [x]      |     [x]      | 
|  add\_to\_diagonal   |   [ ]      |     [ ]      |     [ ]      | 

##GN with QR file breakdown
1. impl/corrction_mixins/sovlers\_qr\_corrector.hpp: **fill, scale, norm2**
2. impl/operators/solvers\_gn\_hessian\_gradient\_operators\_rj\_api.hpp: **product (mat-mat & mat-vec), set_zero, norm2, scale**
3. impl/operators/solvers\_gn_hessian\_gradient\_operators\_weighted\_rj\_api.hpp: **product (mat-mat & mat-vec), dot, set\_zero, scale**
4. impl/operators/solvers\_weighting\_irwls.hpp: **fill, element\_wise\_multiply, product (mat-mat),abs_pow**
5. impl/operators/solvers\_residual\_jacobian\_operators.hpp: **set_zero, norm2**
6. impl/updaters/solvers_default.hpp: **update**
7. impl/updaters/solvers_armijo.hpp: **fill/update, dot, update (5)**

##GN with normal equations file breakdown
1. impl/corrction_mixins/sovlers\_hessian\_gradient\_corrector.hpp: **fill, norm2**
2. impl/corrction_mixins/sovlers\_rj\_corrector.hpp: **fill, scale, norm2**
3. impl/operators/solvers\_gn\_hessian\_gradient\_operators\_hg\_api.hpp: **set\_zero, scale**
3. impl/operators/solvers\_gn\_hessian\_gradient\_operators\_rj\_api.hpp: **product (mat-vec & mat-mat), set_zero, norm2, scale**
4. impl/operators/solvers\_gn_hessian\_gradient\_operators\_weighted\_rj\_api.hpp: **product (mat-vec & mat-mat), dot, set\_zero, scale**
5. impl/operators/solvers\_residual\_jacobian\_operators.hpp: **set_zero, norm2**
5. impl/operators/solvers\_weighting\_irwls.hpp: **fill, element\_wise\_multiply, product (mat-mat),abs_pow**
6. impl/updaters/solvers_default.hpp: **update**
7. impl/updaters/solvers_armijo.hpp: **fill/update, dot, update (5)**
9. impl/updaters/solvers_armijo.hpp: **fill/update, dot, update (5)**


##LM with normal equations file breakdown
1. impl/corrction_mixins/sovlers\_hessian\_gradient\_corrector.hpp: **fill, norm2**
2. impl/corrction_mixins/sovlers\_rj\_corrector.hpp: **fill, scale, norm2**
3. impl/operators/solvers\_lm\_hessian\_gradient\_operators\_hg\_api.hpp: **set_zero, deep_copy, update (4)**
3. impl/operators/solvers\_lm\_hessian\_gradient\_operators\_rj\_api.hpp: **uses gn, set_zero, deep_copy, update (4)**
5. impl/operators/solvers\_residual\_jacobian\_operators.hpp: **set_zero, norm2**
5. impl/operators/solvers\_weighting\_irwls.hpp: **fill, element\_wise\_multiply, product (mat-mat),abs_pow**
6. impl/updaters/solvers_default.hpp: **update**
7. impl/updaters/solvers\_lm\_gain\_factor.hpp: **fill, elementwise\_multiply, dot, update (5)**
8. impl/updaters/solvers\_default.hpp: **update (4)**
9. impl/updaters/solvers\_lm_schedule1.hpp: **update (4)**
10. impl/updaters/solvers\_lm_schedule2.hpp: **update (4)**


#ODE Breakdown

|                      |  Explicit Euler  | AB2          | RK4          |         BDF1 | BDF2         | CN          |
|----------------------|------------------|--------------|--------------|--------------|--------------|--------------
|mat-vec product       |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     |
|mat-mat product       |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     |
| update (3)           |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     |
|update (4)            |   [x]            |     [x]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     |
|update(5)             |   [ ]            |     [ ]      |     [x]      |     [ ]      |     [ ]      |     [ ]     |
|update(6)             |   [ ]            |     [x]      |     [ ]      |     [x]      |     [ ]      |     [ ]     | 
|update(7)             |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
|update(8)             |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [x]      |     [ ]     | 
|update(9)             |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [x]     | 
|update(10)            |   [ ]            |     [ ]      |     [x]      |     [ ]      |     [ ]      |     [ ]     | 
|norm2                 |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
|set_zero              |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
|dot                   |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
| elementwise_multiply |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
| abs_pow              |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
| fill                 |   [ ]            |     [ ]      |     [ ]      |     [ ]      |     [ ]      |     [ ]     | 
| deep_copy            |   [ ]            |     [x]      |     [ ]      |     [x]      |     [x]      |     [x]     | 
| scale                |   [ ]            |     [ ]      |     [ ]      |     [x]      |     [x]      |     [x]     | 
|  add\_to\_diagonal   |   [ ]            |     [ ]      |     [ ]      |     [x]      |     [x]      |     [x]     | 

##Explicit euler file breakdown
1. ode/explicit/impl/ode\_explicit\_euler\_stepper\_impl.hpp: **update (4)**

## AB2 file breakdown
1. ode/explicit/impl/odd\_explicit\_adams\_bashforth2\_stepper\_impl.hpp: **deep_copy, update(4), update (6)**

## RK4 file breakdown
1. ode/explicit/impl/ode\_explicit\_runge\_kutta4\_stepper\_impl.hpp: **update (5), update (10)**

## BDF1 file breakdown
1. ode\_discrete\_time\_jacobian\_impl.hpp: **scale (pybind11 & Eigen), add\_to\_diagonal (dense Eigen)**
2. ode\_discrete\_time\_residual\_impl.hpp: **update (6)**
3. ode\_implicit\_stepper\_arbitrary\_impl.hpp: **deep_copy**
4. ode\_implicit\_stepper\_euler\_impl.hpp: **deep\_copy**

## BDF2 file breakdown
1. ode/implicit/impl/ode\_discrete\_time\_jacobian\_impl.hpp: **scale (pybind11 & Eigen), add\_to\_diagonal (dense Eigen)**
2. ode/implicit/impl/ode\_discrete\_time\_residual\_impl.hpp: **update (8)**
3. ode/implicit/impl/ode\_implicit\_stepper\_arbitrary\_impl.hpp: **deep_copy**
4. ode/implicit/impl/ode\_implicit\_stepper\_bdf2\_impl.hpp: **deep\_copy**


## CN breakdown
1. ode/implicit/impl/ode\_discrete\_time\_jacobian\_impl.hpp: **scale, add\_to\_diagonal (dense Eigen), no pybind11 implementation**
2. ode/implicit/impl/ode\_discrete\_time\_residual\_impl.hpp: **update (9)**
3. ode/implicit/impl/ode\_implicit\_stepper\_arbitrary\_impl.hpp: **deep_copy**
4. ode/implicit/impl/ode\_implicit\_stepper\_cranknicolson\_impl.hpp: **deep\_copy**


#ROM Breakdown

|                      | Galerkin   |    LSPG      |      WLS     |
|----------------------|------------|--------------|--------------| 
|mat-vec product       |   [x]      |     [x]      |     [x]      |
|mat-mat product       |   [x]      |     [x]      |     [x]      |
|update (3)            |   [ ]      |     [ ]      |     [x]      |
|update (4)            |   [ ]      |     [x]      |     [x]      |
|update(5)             |   [ ]      |     [ ]      |     [ ]      |
|update(6)             |   [ ]      |     [x]      |     [ ]      | 
|update(7)             |   [ ]      |     [ ]      |     [ ]      | 
|update(8)             |   [ ]      |     [x]      |     [ ]      | 
|update(9)             |   [ ]      |     [x]      |     [ ]      | 
|update(10)            |   [ ]      |     [ ]      |     [ ]      | 
|norm2                 |   [ ]      |     [x]      |     [x]      | 
|set_zero              |   [x]      |     [x]      |     [x]      | 
|dot                   |   [ ]      |     [ ]      |     [ ]      | 
| elementwise_multiply |   [ ]      |     [ ]      |     [ ]      | 
| abs_pow              |   [ ]      |     [ ]      |     [ ]      | 
| fill                 |   [ ]      |     [ ]      |     [ ]      | 
| deep_copy            |   [x]      |     [x]      |     [x]      | 
| scale                |   [ ]      |     [ ]      |     [ ]      | 
|  add\_to\_diagonal   |   [ ]      |     [ ]      |     [ ]      | 


###Galerkin file breakdown
1. rom/decoder/impl/rom\_linear\_decoder\_pressio\_ops.hpp: **product (mat-vec & mat-mat)**
2. rom/galerkin/impl/projectors/galerkin\_default\_projector\_ortho\_decoder\_jacobian.hpp: **product (mat-vec & mat-mat)**
3. rom/galerkin/impl/projectors/galerkin\_arbitrary\_projector.hpp: **product (mat-vec & mat-mat)**
4. rom/galerkin/impl/continuous\_time\_api/policies/rom\_galerkin\_velocity\_policy.hpp: **set_zero**
5. rom/galerkin/impl/policies/rom\_galerkin\_residual\_policy.hpp:: **set_zero**
6. rom/fom\_states\_management/rom\_manager\_fom_states\_static.hpp: **deep_copy**

##LSPG file breakdown
1. rom/decoder/impl/rom\_linear\_decoder\_pressio\_ops.hpp: **product (mat-vec & mat-mat)**
2. rom/lspg/impl/steady/rom_lspg_steady_system.hpp: **product (mat-vec), norm2**
3. rom/lspg/impl/unsteady/continuous\_time\_api/discrete\_time\_functions/rom\_lspg\_time\_discrete\_jacobian.hpp: **update(4)**
4. rom/lspg/impl/unsteady/continuous\_time\_api/discrete\_time\_functions/rom\_lspg\_time\_discrete\_residual.hpp: **update(6, BDF1), update (8, BDF2), update (9, CN)**
6. rom/fom\_states\_management/rom\_manager\_fom\_states\_static.hpp: **deep_copy**


##WLS file breakdown
1. rom/decoder/impl/rom\_linear\_decoder\_pressio\_ops.hpp: **product (mat-vec & mat-mat)**
2. /impl/rom\_wls\_hessian\_gradient\_system\_api\_impl.hpp: **deep_copy**
3. /impl/rom\_wls\_hessian\_and\_gradient\_sequential\_policy\_impl.hpp: **set_zero, norm2, product (mat-mat, mat-vec)**
3. rom/wls/rom\_wls\_solve\_windows.hpp: **deep_copy**
4. rom/wls/time\_schemes/rom\_wls\_implicit\_euler.hpp: **deep_copy, update (4), update (3)**  
5. rom/wls/time\_schemes/rom\_wls\_bdf2.hpp: **deep_copy, update (4), update (3)**  
6. rom/fom\_states\_management/rom\_manager\_fom\_states\_static.hpp: **deep_copy**


# Pressio ops synatx summary 

### product (Matrix-vector \& matrix-matrix products) 

matrix-vector product,  y = beta * y + alpha * op(A) * x
  
```cpp
  product(::pressio::transpose_type,
    const scalar_type alpha,
    const A_type & A,
    const x_type & x,
    const scalar_type beta,
    y_type & y)
```
  
matrix-matrix product, C = beta * C + alpha * op(A) * op(B)

```cpp
product(::pressio::transpose_type modeA,
  ::pressio::transpose_type modeB,
  const scalar_type alpha,
  const A_type & A,
  const B_type & B,
  const scalar_type beta,
  C_type & C)
{ 
}
``` 

### update 

V = a * V + b * V1	
(four input terms)
	
```cpp
update(T & v, const scalar_t a, const T1 & v1, const scalar_t b)
{
}
```

(three input terms)

```cpp
update(T & v, const T1 & v1, const scalar_t  b)
{
}
```

V = a * V + b * V1 + c * V2
(6 input terms)

```cpp
update(T & v, const scalar_t &a,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c)
{
}
```

(5 input terms)

```cpp
update(T & v,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c)
{
}
```


V = a * V + b * V1 + c * V2 + d * V3

(8 input terms) 

```cpp
update(T  & v, const scalar_t &a,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c,
       const T3 & v3, const scalar_t &d)
{
}
```
(7 input terms)

```cpp
update(T & v,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c,
       const T3 & v3, const scalar_t &d)
{
}
```


V = a * V + b * V1 + c * V2 + d * V3 + e * V4

(10 input terms)

```cpp
update(T & v, const scalar_t &a,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c,
       const T3 & v3, const scalar_t &d,
       const T4 & v4, const scalar_t &e)
{
}
```

(9 input terms)

```cpp
update(T & v,
       const T1 & v1, const scalar_t &b,
       const T2 & v2, const scalar_t &c,
       const T3 & v3, const scalar_t &d,
       const T4 & v4, const scalar_t &e)
{
}
```

### norm2 (l^2 norm)

computes and returns l^2 norm of the vector

```cpp
auto norm2(const vec_type & a)
{
}
```



### set_zero

sets elements to zero

```cpp
set_zero(T & v)
{
}
```

### dot

computes dot product of two vectors, result is a scalar

```cpp
dot(const T0 & vecA, const T1 & vecB)
{
  //compute result
  return result;
}
```
    
### elementwise\_multiply

elementwise multiplication y = beta * y + alpha * x * z

```cpp
elementwise_multiply
(typename ::pressio::containers::details::traits<T>::scalar_t alpha,
 const T & x,
 const T1 & z,
 typename ::pressio::containers::details::traits<T>::scalar_t beta,
 T2 & y)
{
}
```

###abs_pow
abs(y)^x

```cpp
abs_pow(T1 & y,
  const T2 & x,
  const typename ::pressio::containers::details::traits<T1>::scalar_t & exponent)
{
}
```

###fill

o = value

```cpp
fill(T & o, typename T::traits::scalar_t value)
{
}
```


###deep\_copy

```cpp
deep_copy(T2 & dest, const T1 & src)
{
}
```

###scale

o = o * value

```cpp
scale(T & o, typename T::traits::scalar_t value)
{
}
```

###add\_to\_diagonal

adds value to the digaonal of o

```cpp
addToDiagonal(T & o,
typename ::pressio::containers::details::traits<T>::scalar_t value)
{
}
```

**Comment by fnrizzi** [comment]
this will be replaced by just looking at concepts
