### ISSUE TITLE
ode: which implicit time stepping schemes should pressio support?

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#30]
@eparish1 @pjb236 @vbrunini 

Currently, we have BDF1, BDF2. 
Any suggestions on which other **implicit** ones we should have? (this is beside the functionality to let user define an arbitrary scheme), what do you guys think we should natively support?

**Comment by eparish1** [comment]
I would say Crank Nicolson is essential, and a lower priority that would be good would be some implicit higher order Runge-Kutta methods (I'd go to SDIRK4). Here is the ref I always use for DIRK methods:
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20160005923.pdf

**Comment by pjb236** [comment]
I think just having Crank Nicolson and some of the DIRK methods would be fine. Most fancy time-stepping schemes are designed to deal with stiff systems, and if a ROM is stiff I would argue we did something terribly wrong when deriving the ROM.
