### ISSUE TITLE
naming convention 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#301]
## Classes:
  - class name should be CamelCase: `MyStruct`, `MyPodClass`
  - Method names should be lower camel case
  - member names should use trailing `_`: e.g. `int my_data_` (prefer snake case, or lower camel case)
  - public nested type aliases should have `_type`:
  Example: 
  ```cpp
   struct Foo
   {
     using value_type = double;
     void setAlpha(){}
     private:
      int alpha_ = {};
   };
  ```

## Templates
- template parameters should be camel case
  ```cpp
   template<class ValueType>
   class MyClass{}

   template<class ValueType>
   void my_function(ValueType a)
  ```
- locally scoped templates can use `_t` 
  ```cpp
  void my_function(){
    using scalar_t = double;
  }
  ```

## Other

- free functions: use snake case: e.g. `pressio::create_stepper()`
- Metafunctions are functions, so should be named: `is_something`, or `has_something`, `have_matching_execution_space`.

- macros should be all capital 
- enums: 
  ```cpp
  enum class FooList {
    Ok,
    Somethingbad
  };
  ```

**Comment by fnrizzi** [comment]
@MikolajZuzek i am working on making sure code meets the above rules

**Comment by MikolajZuzek** [comment]
Great! I've added the conventions from descriptions to our [Wiki dev guide](https://github.com/Pressio/pressio/wiki/Contributing#style). I've put namespace guideline from #137 there as well.
