### ISSUE TITLE
CI improvements: pressio testing 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#307]
(this section is in progress) 

Must use the #303 

For this work, create your branch off this one [refactor_issue298](https://github.com/Pressio/pressio/tree/refactor_issue298)

- The main thin I like to do is the following: you should use branch [refactor_issue298](https://github.com/Pressio/pressio/tree/refactor_issue298) which involves 3 levels of testing: functional_small, functional_medium, functional_large. 
**I would like to setup CI for pressio for all the variants above such that we build/run tests progressively only if the previous level succeeded**. So the CI should: 
  - A: build/run *functional_small* tests first (these are quick to build) 
  - B: if A succeeds, build/run *functional_medium* tests
  - if B succeeds: build/run *functional_large* tests 

- pressio has existing actions [here](https://github.com/Pressio/pressio/blob/main/.github/workflows/ghactions.yml) 
but these do not follow the model above. So the actions will need to be changed, but just in case you want to take a look. 

- to build tests for pressio using only Eigen and Gtest, you can use the builder as follows: 
  ```
  // assumes environment has CC, CXX defined 
  git clone git@github.com:Pressio/pressio-builder.git
  cd pressio-builder

  ./main_pressio.sh  -dryrun=no -build-mode=Release \
  -target-dir=<your-desired-location> \
  -eigen-path=<full-path-to-install-dir-as-produced-by-builder> \
  -gtest-path=<full-path-to-install-dir-as-produced-by-builder> \
  -cmake-generator-name=default_with_tests \
  -pressio-src=<your-pressio-source-dir>
  ```

- to build tests for pressio using trilinos, Eigen and Gtest, you can use the builder as follows: 
  ```
  to add
  ```

- [ ] add a "cancel on update" action: if one CI build is in progress, and a new code update is pushed, I would like the CI to cancel the current build. See [this](https://github.com/kokkos/kokkos/actions/workflows/cancelling.yml) as an example 

- [ ] when the CI runs the tests, make sure they are run using `ctest -V` because we want to full output

- [ ] check formatting: we can do this later

**Comment by marcinwrobel1986** [comment]
Hello,
after checking [Last run GH actions](https://github.com/Pressio/pressio/actions/runs/1150948377) the intel compilers/MKL do not work very well.
Regarding cancellation it looks like [GitHub Token](https://docs.github.com/en/actions/reference/authentication-in-a-workflow) is created automatically by GH.
I need to take a look at the cancellation, to make it working. Docs [here](https://github.com/potiuk/cancel-workflow-runs)

**Comment by fnrizzi** [comment]
I like to finish this by: 
- completing the cancellation thing 
- add to CI a case with the latest release of Trilinos
