### ISSUE TITLE
solvers: exit when line search compute zero update?

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#31]
Currently the line search terminates when the solution increment drops below 1e-14. If this is the case, then shouldn't we also stop the nonlinear iteration? Having a solution increment that's machine zero in magnitude means we've found a local extrema and there's no escape*. Currently the solver just keeps iterating until it reaches the maximum iteration count, which is a waste of time in my opinion. 

I think we should have the line search output a boolean to tell the nonlinear solver if it found a non-zero solution increment. If it did not, then the nonlinear solver should terminate, perhaps with some kind of warning (or error?) about poor solver convergence. 

*Unless we use levenberg-marquardt or something else that can escape local extrema.

**Comment by mhoemmen** [comment]
Does this need some scaling?  Classical Newton convergence theory bounds the solution error using a constant proportional to the second derivative, divided by the first derivative.  This suggests that if you have a Jacobian that's poorly scaled or with a small minimum singular value, then just measuring the solution increment may not be enough to decide whether to converge.

**Comment by pjb236** [comment]
Yes, it very likely needs some additional scaling, given that the Jacobian usually is poorly scaled. In practice, how is this scaling determined? Is there a more sophisticated line search than Armijo's rule that we could use?

**Comment by mhoemmen** [comment]
Estimating the minimum singular value is harder than solving a linear system.  However, if the problem is a poor choice of units, it's possible to rescale the Jacobian much more cheaply than solving a linear system.  Tpetra has some methods for doing that, if you have a (sparse) matrix in hand.

**Comment by pjb236** [comment]
We don't have access to the matrix itself, we have a MATVEC method for the Jacobian. Also, if we had the matrix it would be dense.

**Comment by mhoemmen** [comment]
@pjb236 When you say "poorly scaled," are you referring to the choice of units (like a row and column scaling of a matrix), or to "poor conditioning" (relating to the singular values etc.)?  If it's the former, then we could either scale in the Jacobian apply implementation (what you call "MATVEC"), or compute an approximate row and column scaling (there are sampling algorithms for doing that).  If it's the latter, then the only real fix is to precondition.

**Comment by pjb236** [comment]
@mhoemmen Both of these are potentially issues I believe, especially the first. We currently scale the POD modes to help with the row scaling. As for preconditioning, there is definitely more that we can do. I know that Jeff Fike did a study of preconditioning approaches for ROMs, I might have to look back over that report to see what worked well.

**Comment by pjb236** [comment]
I think I figured out how to implement this. Since we pass the increment size alpha back to the nonlinear solver from the line search helper, we can add a “break” if alpha is smaller than some tolerance. We could hardcode this tolerance to be something like 1e-14 or make it user-specified.

**Comment by fnrizzi** [comment]
superseded by #425
