### ISSUE TITLE
type_traits: should all detections `is_something` return always false if TPL is not enabled? 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#323]
currently, we have: https://github.com/Pressio/pressio/blob/develop/include/pressio/type_traits.hpp
such that we only include the detection metaf iff the corresponding TPL is enabled. 
We might want to do this: 

```cpp
// always visible
template <typename T, typename enable = void>
struct is_vector_eigen : std::false_type {};

#ifdef PRESSIO_ENABLE_TPL_EIGEN
template <typename T>
struct is_vector_eigen<
  T,
  ::pressio::mpl::enable_if_t<
    is_dynamic_vector_eigen<T>::value or
    is_static_vector_eigen<T>::value
    >
  > : std::true_type{};
#endif 
```

**Comment by fnrizzi** [comment]
maybe this does not make sense becaue if the TPL is not enabled, you know already cannot be true :)

**Comment by fnrizzi** [comment]
@mzuzek i think we should do this what do you think?

**Comment by mzuzek** [comment]
@fnrizzi  No strong objections, but wouldn't do it without a reason either.

What would be the code checking `is_vector_eigen<T>` - enabled and compiled even in no-Eigen build ?
If we don't have such code now - do you think of something specific we can get in future ?

**Comment by fnrizzi** [comment]
yes you are right, i think for now we should make this low priority

**Comment by fnrizzi** [comment]
closing for now while cleaning up, not high priority
