### ISSUE TITLE
update trilinos calls to avoid deprecation

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#336]
CI needs updating

**Comment by fnrizzi** [comment]
ci is breaking

**Comment by marcinwrobel1986** [comment]
> ci is breaking. Trilinos commit to use: ef73d14babf6e7556b0420add98cce257ccaa56b

It is breaking. The commit ef73d14babf6e7556b0420add98cce257ccaa56b is used as told [HERE](https://github.com/Pressio/pressio/blob/a481758227cf8064c6b70f4d6d67384ca315f381/docker_scripts/ubuntu-20.04-gnu_10-eigen_3.3.7-gtest-trilinos_hash-ef73d14babf6e7556b0420add98cce257ccaa56b.dockerfile#L56) is the line when it's used in docker image.

I couldn' built pressio locally as well.
