### ISSUE TITLE
Change documentation style and generator

### ISSUE THREAD

**Issue by marcinwrobel1986** [Pressio/pressio#338]
### TODO:
- change style from [current](https://mcss.mosra.cz) to [wanted](https://github.com/pradyunsg/furo)
- move from [current docs generator](https://doxygen.org/) to [wanted](https://www.sphinx-doc.org/)
- try to use existing `*.md` files

**Comment by fnrizzi** [comment]
couple clarifications: 
- source files are inside: https://github.com/Pressio/pressio/tree/main/docs/pages
- for the time being, please do not worry about formatting/blocks and things like that. **The main priority is to see the overall layout and structure **

**Comment by fnrizzi** [comment]
new source is inside cpp-docs repo, will be moved to docs at the end
