### ISSUE TITLE
ops: performance issue with tpetra-block and eigen pair in ::pressio::ops::product.

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#347]
I noticed some potential performance issues in Pressio while working on unsteady problems with a large number of modes. The problem arises in the matrix-matrix products when working with (block) tpetra FOM types and an eigen ROM type. The specialization for tpetra-eigen product in ops_level3, starting around line 61, is inefficient. We should see if we can replace this with something more efficient that leverages tpetra's multiply. As some reference numbers, performing a matrix-matrix product of  ~200K x 1K matrices took 38 seconds on 10 processors with the tpetra-eigen pair, while it took only about 0.6 seconds with a tpetra-kokkos pair.

**Comment by fnrizzi** [comment]
the first solution to try is to use a Kokkos non-owning view of the eigen matrix and run the kernel via kokkos
