### ISSUE TITLE
Nonlinear solver should complete if line search cannot reduce residual magnitude

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#425]
To prevent the nonlinear solver from running more steps than needed, the line search should tell it to terminate nicely, but with a warning if the line search fails to find an update step that reduces the magnitude of the residual. 

For example, if we reach line 141 in solvers_armijo.hpp, then the nonlinear solver should complete and a warning should be printed to the terminal or log file. For a steady solver, the solver will terminate nicely. For an unsteady solver, we should proceed to the next time step or throw an exception to reduce the time step.

**Comment by eparish1** [comment]
@fnrizzi @pjb236 Let's get this done ASAP. @fnrizzi what's the best path for this. Would you like to do it or would it be helpful if one of us took a stab at it?
