### ISSUE TITLE
Add "basic" backtrack line search

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#488]
We need to add a basic backtracking search that only allows a step if the residual goes down,  \| r(x_{k+1} ) \| \le  \| r(x_k) \|.

**Comment by mzuzek** [comment]
Hi @eparish1,
finally we can have $|r(x_{k+1})| \le |r(x_k)|$ in [GitHub markdown](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions) now :-)
(just wrap your LaTeX math with `$` or `$$`)
