### ISSUE TITLE
c++ 20 build casuses some warning for eigen 3.3.7 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#511]
see this: https://github.com/Pressio/pressio/actions/runs/3604890996/jobs/6074723593

**Comment by mzuzek** [comment]
@fnrizzi I see two warnings replicated in different places:
* `warning: arithmetic between different enumeration types is deprecated [-Wdeprecated-anon-enum-enum-conversion]`
* `warning: bitwise operation between different enumeration types is deprecated [-Wdeprecated-anon-enum-enum-conversion]`

Shall we disable the warnings ?
Or try to upgrade Eigen to [v3.4.0](https://eigen.tuxfamily.org/) in [pressio-builder](https://github.com/Pressio/pressio-builder/blob/main/tpls/tpls_versions_details.sh#L3-L8) and see if that solves the issue ?
I guess we could also fix Eigen to conform to C++20 if that doesn't work (they allow volunteers to contribute).

**Comment by fnrizzi** [comment]
all the C++20 is not high priority ,so let's skip this for now

**Comment by fnrizzi** [comment]
eigen was upgraded to 3.4 so this is not applicable any more
