### ISSUE TITLE
ops: add expression support to eigen matrix-matrix product

### ISSUE THREAD

**Issue by mzuzek** [Pressio/pressio#528]
Eigen overloads of level3 `::pressio::ops::product()` accept native containers and `as_diag_matrix` expression for `A` input. Add support for `subspan` expression and allow expressions for `B` input.
Expand unit tests accordingly to cover new expression cases (and refactor if needed).

refs #526

**Comment by fnrizzi** [comment]
closing for now while cleaning up, not high priority
