### ISSUE TITLE
Add functionality for "viewing" into a  pressio::containers::Matrix

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#53]
For WLS, we need to have the ability to make block updates to a matrix. Specifically, given three matrices:
```
A \in R^{N x K}
B \in R^{N x K}
C \in R^{K s x K s}, where s is an integer >= 1
```
we need to be able to perform the matrix-matrix multiplication `A^T*B` and put the result in a specific block of `C`. For example, in eigen this looks like:
```c++
C.block(start_col,start_row,ncols,nrows) = A.transpose()*B;
```
with ncols = nrows = K

**Comment by fnrizzi** [comment]
@eparish1 you need this for both `containers::Matrix` and `containers::MultiVector`? at some point I would say so, but which one would you need first?

**Comment by mhoemmen** [comment]
Please do consider a syntax compatible with `Kokkos::View` and `mdspan` (which we're hoping will make C++23):
```c++
auto C_block = subspan (C, pair {start_row, end_row}, pair {start_col, end_col});
```
where I'm using C++17 CTAD for `pair`.  It would be great if all "matrix-like" things had a consistent syntax.

**Comment by fnrizzi** [comment]
@mhoemmen yes, definitely a good point! I can follow that.

**Comment by eparish1** [comment]
@fnrizzi  I think containers::Matrix is more pressing than containers::Multivector. From my point of view, I don't think it should be supported for multivector; it seems that accessing certain "blocks" of a multivector is contrary to the concept of a multivector.

**Comment by mhoemmen** [comment]
@eparish1 wrote:
> ... it seems that accessing certain "blocks" of a multivector is contrary to the concept of a multivector.

The Trilinos package Teko depends on being able to make "row blocks" of a (Multi)Vector.  Teko uses this as part of its implementation of block preconditioners ("block" in the "large and sparse" sense).  On the other hand, it might not make sense in Pressio to expose this functionality for (Multi)Vectors.

**Comment by eparish1** [comment]
Clarifying comments: for WLS we need this ability for assigning local elements of the Hessian, which will be of type pressio::containers::Matrix. We _don't_ ever need to access sub-blocks of the basis.

**Comment by fnrizzi** [comment]
@eparish1 @mhoemmen  let me know what you think of this

I just pushed a commit starting to address this. 
I currently have something working for a `containers::Matrix` wrapping Eigen. But will keep working on the rest. Here is an overview: 
```c++
using eigmat_t = Eigen::MatrixXd;
using mat_t = pressio::containers::Matrix<eigmat_t>;

// construct a matrix A with, e.g., 6 rows and 3 cols
mat_t A(6,3);
// get an expression for the subblock for rows 2,3 and cols 1,2
// here, subspan is exclusive of the end index, like Kokkos subview and Python
auto block = A.subspan( std::make_pair(2,4), std::make_pair(1,3) );

// you can now index the block expression like a matrix with 2 rows and 2 cols 
const auto value = block(0, 0);
```
you can also call the expression to return a native object type (e.g. for Eigen this will be the return type of the `block` method for Eigen matrices). This feature will be used in some special cases, e.g. when I need to do operations between a `subspan` expression object and a native Eigen vector for instance.  
```c++
auto nativeExpr = block();
```

@eparish1 if you need to overwrite a subspan with new values, rather that using `(i,j)`, it is better for me to add support for `deep_copy` functionality that takes in a `subspan` expr object and something else to copy data from.

**Comment by fnrizzi** [comment]
@eparish1 
I assume that when you say:
```
A \in R^{N x K}
B \in R^{N x K}
C \in R^{K s x K s}, where s is an integer >= 1
```
A,B are typically MVs that are results of J * phi, correct? Where J is the spatial Jacobian of the FOM ode, and phi is the basis?  Right? So A, B are distributed. C is not.

**Comment by eparish1** [comment]
> `A,B are typically MVs that are results of J * phi, correct? Where J is the spatial Jacobian of the FOM ode, and phi is the basis? Right? So A, B are distributed. C is not.`

@fnrizzi Yes, this is correct in the WLS context. This looks great.

> `if you need to overwrite a subspan with new values, rather that using (i,j), it is better for me to add support for deep_copy functionality that takes in a subspan expr object and something else to copy data from.`

As for overwriting, the specific operation (that I am currently aware of) that we need to do at the end of the day is:
  (*C.data()).block(scol,srow,colSize,rowSize) += (*A.data()).transpose() * (*B.data());

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> ```c++
> auto block = A.subspan( std::make_pair(2,4), std::make_pair(1,3) );
> ```
Prefer nonmember functions.  That way, you can overload them for any kind of object, even for `Kokkos::View` or `mdspan` directly.  For example:
```c++
auto block = subspan(A, make_pair(2,4), make_pair(1,3));
```

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> ...and you can (since A is non-const) also do....

Is the idea that `A` is like `mdarray` or `vector`, and `block` (the view of a subset of rows and columns) is like `mdspan` or `span`?  That is, is `A` a matrix container (owning its storage, etc.) and `block` a view of the elements of that container, with shallow copy semantics?  That's how I would design it.

**Comment by mhoemmen** [comment]
It's funny, I see that "separate containers from views" design as a product of convergent evolution.  I used it in TSQR in 2010 (Matrix vs. MatView).  Teuchos has Array and ArrayView.  The Standard has mdarray and mdspan.  It's just something you need.

**Comment by fnrizzi** [comment]
> @fnrizzi wrote:
> 
> > ...and you can (since A is non-const) also do....
> 
> Is the idea that `A` is like `mdarray` or `vector`, and `block` (the view of a subset of rows and columns) is like `mdspan` or `span`? That is, is `A` a matrix container (owning its storage, etc.) and `block` a view of the elements of that container, with shallow copy semantics? That's how I would design it.

Yes, `A` is a matrix container. And the result of calling subspan is an *expression* that holds a reference to the original object. Agree? 

@mhoemmen A few more details: 
1. Right now, if you call `subspan` on a `const A`, it returns a const-qualified expression and you cannot modify the entries in that `subspan` but only read them with `(i,j)` --- the non-const version instead gives you the obvious. 

2. The code implementing the `subspan` expression is fully outside of the matrix class, so I can easily add support for a nonmember `subspan` free function inside the containers namespace, something like: 
```c++
auto block = pressio::containers::subspan(...);
```

3. Btw, does subview in Kokkos have both `const` and `non-const` versions?

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> 1. Btw, does subview in Kokkos have both `const` and `non-const` versions?

This question relates to the distinction between containers and views in the C++ Standard Library.  `Kokkos::View` is not a good example of either of these.  It's more like a view, but nothing in the C++ Standard (`string_view` and `span`) or proposed for it (as far as I know) that is called a "view" is owning.  Thus, when I say "container" and "view," please ignore `Kokkos::View` and think of the following examples:

  - Containers: `vector`, `string`, `list`, `map`, `Teuchos::Array`
  - Views: `span`, `Teuchos::ArrayView`

Containers and views treat `const`ness differently.  For containers, you can only change their entries if the container is nonconst.  That's how `std::vector` behaves.  Views, in contrast, are like pointers:

  - `T* const`: You can't change the pointer, but you can change the elements to which it points
  - `const T*`: You can change the pointer, but you can't change the elements to which it points

`Kokkos::View` behaves like pointers.  `View<const T*>` means "you can't change the elements."  `View<T*>` means "you can change the elements."  Subview of a `View<T

Taking a subview of a `Kokkos::View` preserves constness of the input `Kokkos::View`.  If you have an input `View<const T*>`, you'll get an output `View<const T*>` (I'm ignoring changes in rank -- the point is that it's still a "View of const.")

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
>     1. Right now, if you call `subspan` on a `const A`, it returns a const-qualified expression and you cannot modify the entries in that `subspan` but only read them with `(i,j)` --- the non-const version instead gives you the obvious.

That makes sense if `A` is a container.  Containers own their storage, and copying them does a deep copy of all the elements.  The classic example of a container is `std::vector`.

`Kokkos::View` is NOT a container.  Copying it does a shallow copy; it's like copying a pointer.  I would call it "view-like."  Views distinguish between "const view" and "view of const," just like pointers distinguish between `T* const` and `const T*`.

If `A` is view-like -- if its copy constructor and copy assignment operator do shallow copies -- then `subspan` should not change constness of element access.

**Comment by fnrizzi** [comment]
@mhoemmen Totally agree. And yes, I remember the distinction (which is tricky :)), thanks for the explanation! I think this is useful to have here. 

In pressio, I decided (but open to change at some point) to design matrices, vectors and mv as **containers** --- in fact, I use references everywhere rather than just passing by value for the obvious reasons.  
So for instance, if you have: 
```c++ 
using k2d_view_t = Kokkos::View<double**>;
using matrix_t   = pressio::containers::Matrix<k2d_view_t>;
auto A = matrix_t("label", 6,3);
//and you do:
auto B = A;
```
this does a deep copy because I implemented the copy constructor of `Matrix` to do that (similarly for Tpetra and Tpetra block) even thought the native, underlying type has view semantics. So I would say the const and non-const subspan expression is ok (for now) --- except the fix needed about the lifetime of the referenced object. 

The main reason for the container semantics is that it was convenient, so far, having pressio own the *data* which is then passed to an application to do some operations on it. I envisioned this would be useful in a scenario where we might need to query multiple *independent* applications objects that rely on data structured distributed in the same way but are independent problems. And also possibly deal with state-less applications, where we just have operations --- far fetched case, but just for making a point. 

Agree?

**Comment by mhoemmen** [comment]
@fnrizzi I'm totally OK with this, and it makes sense that `subview(const SomeContainer<T>&, ...)` returns `SomeView<const T>`.  If you want a way to get a "view of nonconst" for a container, you can always overload `subview` to take a nonconst reference, like this:
```c++
SomeView<T> subview(SomeContainer<T>&, ...);
SomeView<const T> subview(const SomeContainer<T>&, ...);
```

**Comment by fnrizzi** [comment]
> @fnrizzi I'm totally OK with this, and it makes sense that `subview(const SomeContainer<T>&, ...)` returns `SomeView<const T>`. If you want a way to get a "view of nonconst" for a container, you can always overload `subview` to take a nonconst reference, like this:
> 
> ```c++
> SomeView<T> subview(SomeContainer<T>&, ...);
> SomeView<const T> subview(const SomeContainer<T>&, ...);
> ```

Awesome you agree :) 
That is (kind of) exactly what I am doing except that I return a (const) view of the pressio `Matrix` rather than the underlying object itself: 
```c++
SomeView<T> subview(T &, ...);
SomeView<const T> subview(const T&, ...);
```
I will add also the free function `subview` to make things more complete.

**Comment by fnrizzi** [comment]
cc77137bb42371a9cd18ce80c2521b096a736dba
