### ISSUE TITLE
nonlinear solvers: redesign ideas

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#549]
# 1. solving system of `n` nonlinear eq in `n` variables (root-finding)

In python they have this: https://docs.scipy.org/doc//scipy-0.15.0/reference/generated/scipy.optimize.root.html#id1

## pressio

(1) Newton method:
```c++
solver = create_newton_solver(problem, linearSolver);
```

- problem meets the *determined* residual/jacobian api [link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/rj.html))

- jacobian is whatever (exact or not) the user implements

- useful references:
  - https://einspem.upm.edu.my/journal/fullpaper/vol6no1/4.%20waziri%20edit.pdf
  - http://www.dmsa.unipd.it/~berga/Teaching/quasinewton.pdf

(2) quasi-newton:

```c++
solver = create_broyen1_solver(problem, linearSolver)
solver = create_broyen2_solver(problem, linearSolver)    
// etc

// which we could potentially condense behind a single function (have to figure out if feasible):
solver = create_quasi_newton_solver(problem, linearSolver, method)
```

- *we don't have this yet, but looking ahead of what it could be like*

- problem meets the *determined* residual api with an initial jacobian to start from possily, 
  or if no jaobian then it is approximate by pressio directly, anyway we can flush this out later

- jacobian is approximated in pressio somehow, this depends on the method

- for example: 
   - minpack *hybr*: 
     - https://www.math.utah.edu/software/minpack/minpack/hybrd.html

   - broyden1: 
     - https://en.wikipedia.org/wiki/Broyden%27s_method#Solving_a_system_of_nonlinear_equations
     - https://github.com/scipy/scipy/blob/88fc9b098c4e9604b280f16f7c5530b81ab1d45c/scipy/optimize/nonlin.py#L909
     - http://www.dmsa.unipd.it/~berga/Teaching/quasinewton.pdf

   - broyden2: 
     - https://en.wikipedia.org/wiki/Broyden%27s_method#Solving_a_system_of_nonlinear_equations
     - https://github.com/scipy/scipy/blob/88fc9b098c4e9604b280f16f7c5530b81ab1d45c/scipy/optimize/nonlin.py#L1002
     - http://www.dmsa.unipd.it/~berga/Teaching/quasinewton.pdf

- references:
   - http://www.dmsa.unipd.it/~berga/Teaching/quasinewton.pdf

<br>
<br>
<br>
<br>

# 2. non-linear least squares

(1) ```solver = create_gauss_newton(problem, linearSolverForNoramlEq)```

- problem meets the *overderdetermined* [residual/jacobian api]([link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/rj.html))) 
  OR the hessian/gradient API [link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/hg.html)

(2) ```solver = create_gauss_newtonQR(problem, solverforQR)```

- problem meets the *overderdetermined* [residual/jacobian api]([link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/rj.html))) 

(3) ```solver = create_lm(problem, linearSolverForNoramlEq)```

- problem meets the *overderdetermined* [residual/jacobian api]([link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/rj.html))) 
  OR the hessian/gradient API [link](https://pressio.github.io/pressio/components/nonlinearsolvers_concepts/hg.html)

<br>
<br>
<br>
<br>

# 3. generic optimization (we can add this later if needed)
 
## Python 

- https://docs.scipy.org/doc//scipy-0.15.0/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

Implemented as different functions:

- https://github.com/scipy/scipy/blob/88fc9b098c4e9604b280f16f7c5530b81ab1d45c/scipy/optimize/_minimize.py#L408

## pressio 

(a)
```c++ 
void minimize_powell( args_TBD );
minimizer = create_powell_minimizer( args_TBD );
```

  - https://en.wikipedia.org/wiki/Powell%27s_method#:~:text=Powell's%20method%2C%20strictly%20Powell's%20conjugate,and%20no%20derivatives%20are%20taken.&text=)%20are%20passed%20in%20which%20are,normals%20aligned%20to%20each%20axis.

(b) 
```c++
void minimize_bfgs( args_TBD )
minimizer = create_bfgs_minimizer(...);
```

  - https://en.wikipedia.org/wiki/Broyden%E2%80%93Fletcher%E2%80%93Goldfarb%E2%80%93Shanno_algorithm

(c) 
```c++
void minimize_nelder_mead( args_TBD )
minimizer = create_nelder_mead_minimizer(...);
```

  - https://en.wikipedia.org/wiki/Nelder%E2%80%93Mead_method

(other variants)

some questions:
  - would it make sense to make the minimizer a class? for example for multiple calls so that expensive operators 
    are not computed multiple times

**Comment by pjb236** [comment]
This looks good, but I have few questions:

1. Which Quasi-Newton Algorithms start from an initial Jacobian? I've never heard of any, but it's not my area of expertise.
2. What situations would we want to call a minimizer multiple times? Are you thinking of a case when we minimize from multiple initial conditions to improve robustness?

**Comment by sdbond** [comment]
Broyden's method updates the Jacobian in the direction of the step using a secant approximation.  The initial guess for the Jacobian is typically set to the identity, and as the method progresses, it updates the Jacobian in each step direction.  This gives you an O(N) update at each step instead of O(N^2) for the entire Jacobian.

**Comment by fnrizzi** [comment]
Thanks @sdbond for your input!

@pjb236 
> What situations would we want to call a minimizer multiple times? Are you thinking of a case when we minimize from multiple initial conditions to improve robustness?
thinking about the general case where we want to run minimization at each time step fore example. 
But in general, instantiating a minimizer, calling it multiple times without redoing all initialization every time. Even for the case you suggest , it would make sense (IMO) to instantiate the minimizer only once

**Comment by pjb236** [comment]
@fnrizzi agreed on not instantiating the minimizer every time step, can't believe I didn't think of that. I guess I've been too focused on steady LSPG.

**Comment by fnrizzi** [comment]
- newton
  - [ ] rj and rj fused 
  
- gauss-newton neq 
  - [ ] rj, rj fused 
  
- weighted gauss-newton neq 
  - [ ] rj, rj fused 

- lm neq 
  - [ ] rj, rj fused 
  
- weighted lm neq 
  - [ ] rj, rj fused

**Comment by fnrizzi** [comment]
#606
