### ISSUE TITLE
ode: time-discrete funcs: make tag an argument rather than using sfinae   

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#57]
ode: time-discrete funcs: make tag an argument rather than using sfinae. 
Overloading is faster in general. 

thanks to @mhoemmen for the suggestion

**Comment by mhoemmen** [comment]
awww I think I made more work for you :-)

**Comment by fnrizzi** [comment]
> awww I think I made more work for you :-)

Maybe starting from Q2 you can help me out with the core code :) I can leave this hanging until then! :) haha!

**Comment by mhoemmen** [comment]
I'm trying to find some good talks to back up this redesign suggestion.  Here's an example: https://youtu.be/NPWQ7xKfIHQ?t=948
