### ISSUE TITLE
tpetra (block): allow users to instantiate ROMs with Eigen types only when using host exe space 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#60]
tpetra: allow users to do ROMs using Eigen only with a host exe space. In general, it would be better to use Kokkos data types for ROMs with tpetra.

**Comment by mhoemmen** [comment]
kokkos-kernels slowly gets more and more BLAS functionality.  I've also gotten a stub cuSOLVER program to build and I'm working on a cuSOLVER-based TSQR.  cuSOLVER has a LOT of features so I suspect we could remove the host-only dependency for CUDA builds at least.  We'll have issues if we have to support other architectures that don't have a nice library like cuSOLVER, but we could still use Eigen as a fall-back until we get native implementations.

**Comment by fnrizzi** [comment]
@mhoemmen agreed! Also, to articulate more, what I meant more broadly with this issue is that I believe we need to encourage/prefer Kokkos-based ROMs when Kokkos is involved either directly or indirectly like in Tpetra. And Eigen (or something else) be the alternative when Kokkos is not involved. 

P.s. I have already a draft working of Kokkos-based ROMs when the FOM is purely Kokkos-based but it is limited to normal equations, so your TSQR addition will be great to allow us to support implementations, namely normal-equations and QR-based.
