### ISSUE TITLE
CI: status of current pipelines 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#614]
make summary/table of current pipelines detailing compiler, OS, TPLs versions, C++ standard used, etc

should look at: 

https://github.com/Pressio/pressio/blob/main/.github/workflows/ci-workflow.yml

and 

https://github.com/Pressio/pressio/tree/main/docker_scripts

**Comment by antoinemeyer5** [comment]
## Workflow

Def: A workflow is made up of one or more jobs.

List of Pressio workflows: *https://github.com/Pressio/pressio/actions*

| workflow name             | file              | goal                              | jobs number   |
|---------------------------|-------------------|-----------------------------------|---------------|
| `Deploy docs`             | deploy_docs.yml   | Generates and deploys the site    | 1             |
| `github-linux`            | ci-workflow.yml   | Run jobs                          | 3             |
| pages-build-deployment    | ??                | ??                                | ??            |

## Job

Def: A job can have a matrix of different job configurations (we use Docker images).

| workflow name     | job name              | configurations number | status    |
|-------------------|-----------------------|-----------------------|-----------|
| `Deploy docs`     | build-and-deploy-docs | NaN                   | OK        |
| `github-linux`    | CI                    | 8                     | 8/8       |
| `github-linux`    | CI-trilinos           | 2                     | 2/2       |
| `github-linux`    | CI-cxx20              | 5                     | **3/5**   |

## Pipelines

When you push code, workflows `Deploy docs` and `github-linux` will be triggered and will run.

To check that jobs run smoothly on different configurations, **Docker images** are used in GitHub Actions for testing purposes.

Images currently used: **6** (2 fedora, 1 intel and 3 ubuntu)

| ID    | docker image name                                                          |
|-------|----------------------------------------------------------------------------|
| F0    | fedora-34-clang_12-eigen_3.3.7-gtest.dockerfile                            |
| F1    | fedora-34-gnu_11-eigen_3.3.7-gtest.dockerfile                              |
| I0    | intel_oneapi-eigen_3.3.7-gtest.dockerfile                                  |
| U0    | ubuntu-20.04-clang_9-eigen_3.3.7-gtest.dockerfile                          |
| U1    | ubuntu-20.04-gnu_10-eigen_3.3.7-gtest-trilinos_hash-ef[...]6b.dockerfile   |
| U2    | ubuntu-20.04-gnu_9-eigen_3.3.7-gtest.dockerfile                            |

Images currently not used: 14 (6 fedora and 8 ubuntu)

List of all Docker images: *https://github.com/Pressio/pressio/tree/main/docker_scripts*

## Docker images

Readme here: *https://github.com/Pressio/pressio/blob/main/docker_scripts/ReadMe.md*

| ID    | OS            | compiler  | C++ template library  | GoogleTest    | Trilinos version  |
|-------|---------------|-----------|-----------------------|---------------|-------------------|
| F0    | fedora-34     | clang_12  | eigen_3.3.7           | gtest         |                   |
| F1    | fedora-34     | gnu_11    | eigen_3.3.7           | gtest         |                   |
| I0    | Ubuntu 18.04  | GNU 9     | eigen_3.3.7           | gtest         |                   |
| U0    | ubuntu-20.04  | clang_9   | eigen_3.3.7           | gtest         |                   |
| U1    | ubuntu-20.04  | gnu_10    | eigen_3.3.7           | gtest         | trilinos 13.0.0   |
| U2    | ubuntu-20.04  | gnu_9     | eigen_3.3.7           | gtest         |                   |

## `github-linux` workflow details

| job name      | docker image ID   | mode      | status    |
|---------------|-------------------|-----------|-----------|
| CI            | U2                | Release   | OK        |
| CI            | U2                | Debug     | OK        |
| CI            | U0                | Release   | OK        |
| CI            | U0                | Debug     | OK        |
| CI            | F1                | Release   | OK        |
| CI            | F1                | Debug     | OK        |
| CI            | F0                | Release   | OK        |
| CI            | F0                | Debug     | OK        |
| CI-trilinos   | U1                | Release   | OK        |
| CI-trilinos   | U1                | Debug     | OK        |
| CI-cxx20      | **ubuntu-20.04_gnu-11_eigen-3.3.7_gtest**   |Release|**undefined**|
| CI-cxx20      | **ubuntu-20.04_clang-12_eigen-3.3.7_gtest** |Release|**undefined**|
| CI-cxx20      | F1                | Release   | OK        |
| CI-cxx20      | F0                | Release   |**cancelled**|
| CI-cxx20      | I0                | Release   |**failing**|

**Issues here: 2 images are used when they don't exist**

https://github.com/Pressio/pressio/blob/a6a86b649fea045e6b735a7bb0a7d28cf2960a73/.github/workflows/ci-workflow.yml#L235

https://github.com/Pressio/pressio/blob/a6a86b649fea045e6b735a7bb0a7d28cf2960a73/.github/workflows/ci-workflow.yml#L236

I don't know why and how is it possible..
