### ISSUE TITLE
add span for viewing a contiguous subset of vector

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#63]
see #53

**Comment by fnrizzi** [comment]
6cfc07a2c4a47818fb3c589cc47c9e86a5f44854

**Comment by fnrizzi** [comment]
cc77137bb42371a9cd18ce80c2521b096a736dba

**Comment by fnrizzi** [comment]
@eparish1  @mhoemmen 
The span works as follows: 
```c++
using native_t = Eigen::VectorXd; 
using vec_t = pressio::Vector<native_t>;
vec_t a(34);
// ...
// fill a
// ...

// construct span (for now) passing the index of first element, extent of the span 
// e.g. to get a ``non-const view'' to a(2:6) inclusive.
auto sub = pressio::containers::span(a, 2, 5); 
// you can index the expression sub[i] where 0 <= i < 5 : 
sub[0] = 6.6;   // which will overwrite a[2]

// or you can get the native expression/object representing the span by doing: 
// but you don't need this in most cases 
auto nativeObj = sub();

// you can also do mvec prod vec: 
using eigen_mat_t = Eigen::MatrixXd;
auto mv = pressio::MultiVector<eigen_mat_t>(nRows, 5);
vec_t c(nRows);
pressio::containers::ops::product(mv, sub, c);
```

@eparish1 you can merge develop into WLS

**Comment by fnrizzi** [comment]
43d87e3479ae1859e2e034a4fcc467e295154e63

**Comment by mhoemmen** [comment]
@fnrizzi these two comments don't seem consistent:
> `// e.g. to get a ``non-const view'' to a(2:6) inclusive.`
> `auto sub = pressio::containers::span(a, 2, 5);`
> `// you can index the expression sub[i] where 0 <= i < 5 :`

**Comment by fnrizzi** [comment]
@mhoemmen 
I think I know the reason behind your comment :) 
Let me know if this explains it better. 

Currently, span is constructed by passing 
1. the vector object  
2. the index of the element identifying the beginning of the span
3. the extent of the span 
 
So if I want a span including elements a[2,3,4,5,6], I do: 
```c++
auto sub = pressio::containers::span(a, 2, 5);
```
In the span, one uses the regular indexing, i.e. `sub[i]` for `0<= i < 5` since the span has extent = 5;
So sub[0] corresponds to a[2], sub[1] to a[3], etc. 

Does this answer your comment?

**Comment by mhoemmen** [comment]
@fnrizzi wrote:
> Does this answer your comment?

Yes; thanks!  (Note that `subspan` and `Kokkos::subview` both take pairs to specify a contiguous index range.  The equivalent to your example would be `subspan(a, pair {2, 7});`.)

**Comment by fnrizzi** [comment]
@mhoemmen yes, you are right! I will add that constructor too ---also because that is what I actually used for `subspan` so it makes sense to keep things consistent. thanks for pointing this out!
