### ISSUE TITLE
cleanup old branches related to documentation

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#630]
the followign branches add new content/pages to the docs 

<img width="1289" alt="image" src="https://github.com/Pressio/pressio/assets/18708772/579581f2-1a17-4447-823e-3636541fb1d6">

i like to move the new content added by these into a single issue so that i can delete the branches but not lose the work which will be resumed later

**Comment by antoinemeyer5** [comment]
There are 8 branches here:
- [ ] 413-multi-vector-update
- [ ] 413-max
- [ ] 413-min-max
- [ ] 413-extent
- [ ] 413-dot
- [ ] 413-deep-copy
- [ ] 413-add-to-diagonal
- [ ] 413-abs

And they are now in the branch named: `AM-TODO`

**Comment by fnrizzi** [comment]
i did not want to have a new branch, read here please: "move the new content added by these into a single issue" 
i like to have an issue and put all content there

**Comment by antoinemeyer5** [comment]
So I copy-paste raw code?

**Comment by fnrizzi** [comment]
just make an issue, put separate sections and for each section you put the code or you can just upload the file

**Comment by antoinemeyer5** [comment]
Issue #631 with work carry out by [thearusable](https://github.com/thearusable) on issue https://github.com/Pressio/pressio/issues/413
