### ISSUE TITLE
Drop support for C++ 14

### ISSUE THREAD

**Issue by cz4rs** [Pressio/pressio#640]
> Can we actually drop support for C++14? I can see that Eigen defaults to C++14, but Trilinos, Kokkos (and possibly more TPLs) require C++17. 

_Originally posted by @cz4rs in https://github.com/Pressio/pressio/pull/634#discussion_r1308824913_

Remove support for C++14 as soon as no users depend on it.

**Comment by fnrizzi** [comment]
done already
