### ISSUE TITLE
Add new API for pre-computatable systems (linear, quadratic, etc.)

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#65]
After reading the current Pressio paper, I think something that should definitely be planned for future versions of the code is to support ROM approaches for systems that are pre-computable; e.g., linear systems, quadratic systems. I think this is important because ROMs are widely applied to these systems, and this should be something that is included in any ROM code. For example, for the linear system:

dx/dt = Ax,

the ROM reads,

d\hat{x}dt = \Phi^T A \Phi \hat{x} 

We should 100% have an API that supports precomputing Phi^T A \Phi. We could do this by having an API that passes A. The exact design should be discussed obviously, but I wanted to point out that I view this as an important issue.

**Comment by fnrizzi** [comment]
@eparish1 really good point, in fact I am currently working on it :)

**Comment by fnrizzi** [comment]
@eparish1 do you have a suggestion for what the API should look like? if so, please share here :)

**Comment by eparish1** [comment]
I currently do not, and would need to think about it more. Things that I think should be considered are parametric separability, polynomial nonlinearities, and linearized ROMs about an operating point. I'd need to do some thinking if that all naturally fits into one API, or if the should have separate ones.

**Comment by fnrizzi** [comment]
we can start with something simple, and then make add features
