### ISSUE TITLE
add new trilinos pipeline for CI and step-by-step guide for how to add a new one

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio#650]
1. i like to add a new pipeline to the CI that uses this: 
```
commit 702aac58950c2839cae8cbe7f031ffec5d2fb5cf
Merge: 486072279ed 81dfde39d85
Author: trilinos-autotester <trilinos@sandia.gov>
Date:   Tue Apr 18 17:02:05 2023 -0500

    Merge Pull Request #11800 from gsjaardema/Trilinos/seacas-snapshot-04-18-23

    Automatically Merged using Trilinos Pull Request AutoTester
    PR Title: Automatic snapshot commit from seacas at 701da54f38
    PR Author: gsjaardema
```

2. and a step bystep guide to put somewhere (for now in a issue is fine) where we detail how to add a new CI build for trlinos if we needed on. something like 
```
step 1: pick a trilinos commit you like to use 
step 2: 
   a. add a new docker script inside ... where ... and execute it via: 
    ... 
   b. publish the new image t.... 

   
step N: ...
```

**Comment by cz4rs** [comment]
**How to test with a new Trilinos version**
- Pick a Trilinos version to use. You can use a tag or a commit hash.
- Add another image definition to `ci-docker.yml` (see 6231ba9b5d3b11e820951f8cdb83ffcdb0c75577).
- Enable pushing images from branches to get the new image into registry (see 38a7fb5e5c03a53aa77b711de53855614582293c).
  - Normally pushing only happens on `develop`. In this case we need the new image to be pushed from branch to be able to run the tests from `ci-trilinos.yml`.
- You need to let CI run at least once for the image to be pushed to container registry.
- Once the image is published, remember to disable pushing from branches (see b9540c756bb2c6de3fb24e2c78d3f2c06c524768)
- You can now enable testing using the newly added image in `ci-trilinos.yml` (see 496df2d33f085518e5897baad825c893b588367d).

See how Trilinos `702aac5` was added in #651.

---
**Debugging notes**
You can double-check Trilinos version in `Build and Push Docker images for Github Container Registry` step:
```
#17 46.23 HEAD is now at 702aac58950 Merge Pull Request #11800 from gsjaardema/Trilinos/seacas-snapshot-04-18-23
```
You should also see a successful push at the end of that step:
```
#20 pushing manifest for ghcr.io/pressio/ubuntu-gnu-trilinos-11:702aac5@sha256:0428a42abee7e5c322c0a8527b0653b326bb59486fa7246a90d629742400a330 3.4s done
```
