### ISSUE TITLE
Improve behavior for backtrack line search in the event of success.

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#692]
In the backtrack line search, we:

1. Compute the residual and Jacobian
2. Compute a "test state" which is the Newton update
3. Evaluate the residual about this test state to check if the residual norm is decreasing.

If the line search passes, we should keep track that we have already computed the residual (and potentially the Jacobian if we are using the combined residualAndJacobian API) about the new state, and thus we don't need to re-compute anything. As is, the backtrack line search doubles the cost of the ROM.

**Comment by fnrizzi** [comment]
yes good point

**Comment by cwschilly** [comment]
@eparish1 @fnrizzi 

Just to clarify, will an `Updater` ever compute the Jacobian? From what I can tell, the updaters will call this objective function that only computes the residual and not the Jacobian:

```cpp
  auto objective = [&reg, &system](const state_type & stateIn){
    auto & r = reg.template get<ResidualTag>();
    system.residualAndJacobian(stateIn, r, {});
    return ::pressio::ops::norm2(r);
  };
```

**Comment by fnrizzi** [comment]
this was discussed and solved, nothing to do for now
