### ISSUE TITLE
#6 Required additions for WLS with Kokkos

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#76]
For integrating with Kokkos, we need:
- [ ] Span functionality, which allows us to access a span of a vector. The Eigen interface we have setup is, e.g., 
```
 auto xSpan = containers::span(x, spanStartIndex, spanSize);
``` 

(I'll keep this updated as we move on)

**Comment by mhoemmen** [comment]
Would be nice to make this consistent with `Kokkos::subview`, mdspan `subview`, and Python, by passing in a half-exclusive pair for the index range:
```cpp
auto xSpan = containers::span(x, std::pair{spanStartIndex, spanSize}); // C++17 CTAD
```
