### ISSUE TITLE
#6 add functionality for tpetra_block

### ISSUE THREAD

**Issue by eparish1** [Pressio/pressio#78]
To get WLS working with tpetra_block, we need to add functions for:

- [ ] containers::ops::prod for Ay, A is a tpetra_block object and y an expression
- [ ] containers::ops::do_update for tpetra_block multivector
- [ ] containers::ops::dot for C = A^T B, where C is an expression and A,B are tpetra_block 

Currently these are in as dummy functions for compiling; dummy functions print error messages.

**Comment by fnrizzi** [comment]
@eparish1 will have these after you have the app with tpetra block

**Comment by fnrizzi** [comment]
v0.3.1
