### ISSUE TITLE
Galerkin ROM for residual API?

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#86]
I think we can use the residual API to create Galerkin ROMs for systems of the form:

M dx/dt = f(x,t)

This would be useful for explict and implicit time-stepping schemes, both of which require inverting the mass matrix M. 

Galerkin for the residual API could be set up by solving the following equations for each Gauss-Newton update:
 
Phi^T J Phi du = Phi^T r 

Where:

r = time-discrete residual vector
J = time-discrete Jacobian matrix
Phi = POD basis
Phi^T = transpose Phi

Please let me know if this seems useful/mathematically sound. @eparish1 @fnrizzi

**Comment by eparish1** [comment]
I think having Galerkin is always useful, so yes I agree. For explicit schemes, I think it would be better to manipulate things a little bit to simplify the solve. Also, just a note that in the case that the bases are M-orthogonal and we have an explicit method, we can do a completely explicit update for the state. I wrote down the math to be precise.


[main.pdf](https://github.com/Pressio/pressio/files/4299816/main.pdf)

**Comment by fnrizzi** [comment]
See release v0.3.1

**Comment by fnrizzi** [comment]
@pjb236 @eparish1 I think it is working, but we should verify.

**Comment by pjb236** [comment]
I've been looking over the math and it seems like hyper reduction for a Galkerin ROM requires the velocity API. This is because we need to reconstruct the velocity on the entire sample mesh to add it to the state time derivative. To reconstruct the velocity, we need a distinct routine to compute it, which is impossible with the residual API. See the attached PDF for the math. 

[galerkin_hyperreduction.pdf](https://github.com/Pressio/pressio/files/4691033/galerkin_hyperreduction.pdf)

**Comment by eparish1** [comment]
In your attachment, are you then defining Galerkin ROM as phi^T times the residual, i.e., phi^T r(x^{n+1} ,x^n) = 0? If so, I I agree with what you have, and I also agree that this is usually how Galerkin is implemented. I would say that there isn't a _unique_ definition of hyper-reduction for the Galerkin ROM, however. We could get around this by just hyper-reducing the whole residual, which I believe should fix the issue. I actually think this is a little more sound mathematically. You can derive this type of Galerkin as either (a) a residual orthogalization process in a ''hyper reduced" norm or (b) as a residual minimization process in a slightly different norm (second page attached).
[main.pdf](https://github.com/Pressio/pressio/files/4692314/main.pdf)

**Comment by pjb236** [comment]
To answer your question yes, I am defining the Galerkin ROM as the projection of the residual onto the POD basis. 

I have a question about the minimization statement on the second page of the pdf. Does Gamma need to be SPD? If Gamma is formed from sparse sampling matrices, then it seems like it would be rank-deficient by definition. If this is the case, then the SPD requirement rules out hyper-reduction. If Gamma can be positive semi-definite, then hyper-reduction is ok I think.

**Comment by eparish1** [comment]
Good question. It needs to admit the cholesky decomposition. SPD gives this
for sure, but I need to verify if you can do this for rank deficient. I
think it is fine but need to verify it.
