### ISSUE TITLE
Serial build with tests broken

### ISSUE THREAD

**Issue by pjb236** [Pressio/pressio#97]
@fnrizzi, I'm trying to build pressio with Eigen on a MacBook and it seems like pressio is trying to access stuff for Kokkos for the optimizer tests:

In file included from 
pressio/unit_tests/../packages/pressio_solvers.hpp:78,
                 from 
pressio/unit_tests/../packages/pressio_optimizers.hpp:58,
                 from 
pressio/unit_tests/optimizers/optimizers_parameter_list.cc:3:
pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:103:35: error: ‘is_dense_matrix_wrapper_kokkos’ is not a member of ‘pressio::containers::meta’; did you mean ‘is_dense_matrix_wrapper_eigen’?
  103 |     (::pressio::containers::meta::is_dense_matrix_wrapper_kokkos<MatrixT>::value or
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   is_dense_matrix_wrapper_eigen
pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:103:76: error: ‘::value’ has not been declared
  103 |     (::pressio::containers::meta::is_dense_matrix_wrapper_kokkos<MatrixT>::value or
      |                                                                            ^~~~~
pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:104:35: error: ‘is_multi_vector_wrapper_kokkos’ is not a member of ‘pressio::containers::meta’; did you mean ‘is_multi_vector_wrapper_eigen’?
  104 |      ::pressio::containers::meta::is_multi_vector_wrapper_kokkos<MatrixT>::value)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   is_multi_vector_wrapper_eigen
/Users/pblonig/Software/pkgs/pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:104:76: error: ‘::value’ has not been declared
  104 |      ::pressio::containers::meta::is_multi_vector_wrapper_kokkos<MatrixT>::value)
      |                                                                            ^~~~~
pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:101:8: error: parse error in template argument list
  101 |   mpl::enable_if_t<
      |        ^~~~~~~~~~~~
  102 |     ::pressio::solvers::linear::details::traits<tag>::direct and
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  103 |     (::pressio::containers::meta::is_dense_matrix_wrapper_kokkos<MatrixT>::value or
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  104 |      ::pressio::containers::meta::is_multi_vector_wrapper_kokkos<MatrixT>::value)
      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  105 |     >
      |     ~   
pressio/unit_tests/../packages/solvers/src/linear/solvers_linear_solver.hpp:110:50: error: ‘KokkosDirect’ in namespace ‘pressio::solvers::linear::impl’ does not name a template type
  110 |   using type = ::pressio::solvers::linear::impl::KokkosDirect<tag, MatrixT>;

**Comment by fnrizzi** [comment]
@pjb236 fixed it, you can rebase your branch
